(function(g){var window=this;'use strict';var JPa=function(a,b){return g.Pb(a,b)},KPa=function(a,b){b=b instanceof g.Ic?b:g.Oc(b,/^data:image\//i.test(b));
a.src=g.Jc(b)},LPa=function(a){if(a instanceof g.Xh)return a;
if("function"==typeof a.Dg)return a.Dg(!1);if(g.La(a)){var b=0,c=new g.Xh;c.i=function(){for(;;){if(b>=a.length)throw g.ci;if(b in a)return a[b++];b++}};
c.next=c.i.bind(c);return c}throw Error("Not implemented");},MPa=function(a,b,c){if(g.La(a))try{g.Cb(a,b,c)}catch(d){if(d!==g.ci)throw d;
}else{a=LPa(a);try{for(;;)b.call(c,a.next(),void 0,a)}catch(d){if(d!==g.ci)throw d;}}},B6=function(a){g.rk(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.Ra()).toString(36));
return a},C6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.wk(a.l,b,c)},NPa=function(a,b){var c=[];
MPa(b,function(d){try{var e=g.lr.prototype.l.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.kr(e)&&c.push(d)},a);
return c},OPa=function(a,b){NPa(a,b).forEach(function(c){g.lr.prototype.remove.call(this,c)},a)},PPa=function(a){if(a.V){if(a.V.locationOverrideToken)return{locationOverrideToken:a.V.locationOverrideToken};
if(null!=a.V.latitudeE7&&null!=a.V.longitudeE7)return{latitudeE7:a.V.latitudeE7,longitudeE7:a.V.longitudeE7}}return null},QPa=function(a,b){g.jb(a,b)||a.push(b)},D6=function(a){var b=0,c;
for(c in a)b++;return b},RPa=function(a){try{return g.B.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},E6=function(a){if(g.B.JSON)try{return g.B.JSON.parse(a)}catch(b){}return RPa(a)},SPa=function(a,b,c,d){var e=new g.fk(null,void 0);
a&&g.gk(e,a);b&&g.hk(e,b);c&&g.ik(e,c);d&&(e.J=d);return e},F6=function(a,b){g.Ju[a]=!0;
var c=g.Hu();c&&c.publish.apply(c,arguments);g.Ju[a]=!1},G6=function(a){this.name=this.id="";
this.clientName="UNKNOWN_INTERFACE";this.app="";this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.ei;this.model=this.brand="";this.year=0;this.chipset=this.osVersion=this.os="";this.mdxDialServerType="MDX_DIAL_SERVER_TYPE_UNKNOWN";a&&(this.id=a.id||a.name,this.name=a.name,this.clientName=a.clientName?a.clientName.toUpperCase():"UNKNOWN_INTERFACE",this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=
a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",TPa(this,a.capabilities||""),UPa(this,a.experiments||""),this.brand=a.brand||"",this.model=a.model||"",this.year=a.year||0,this.os=a.os||"",this.osVersion=a.osVersion||"",this.chipset=a.chipset||"",this.mdxDialServerType=a.mdxDialServerType||"MDX_DIAL_SERVER_TYPE_UNKNOWN",a=a.deviceInfo)&&(a=JSON.parse(a),this.brand=a.brand||"",this.model=a.model||"",this.year=a.year||0,this.os=a.os||"",
this.osVersion=a.osVersion||"",this.chipset=a.chipset||"",this.clientName=a.clientName?a.clientName.toUpperCase():"UNKNOWN_INTERFACE",this.mdxDialServerType=a.mdxDialServerType||"MDX_DIAL_SERVER_TYPE_UNKNOWN")},TPa=function(a,b){a.capabilities.clear();
g.To(b.split(","),g.Pa(JPa,VPa)).forEach(function(c){a.capabilities.add(c)})},UPa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},H6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||"";this.idType=a.screenIdType||"normal"},I6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},WPa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid,screenIdType:a.idType}},XPa=function(a){return new H6(a)},YPa=function(a){return Array.isArray(a)?g.Se(a,XPa):[]},J6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+((a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+",idType:"+a.idType+"}"):"null"},K6=function(a){return Array.isArray(a)?"["+g.Se(a,J6).join(",")+"]":"null"},L6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},ZPa=function(a){return g.Se(a,function(b){return{key:b.id,
name:b.name}})},M6=function(a,b){return g.fb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},N6=function(a,b){return g.fb(a,function(c){return I6(c,b)})},$Pa=function(){var a=(0,g.jz)();
a&&OPa(a,a.i.Dg(!0))},O6=function(){var a=g.mz("yt-remote-connected-devices")||[];
g.zb(a);return a},aQa=function(a){if(g.kb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Se(a,function(d,e){return 0==e?d:d.substring(c.length)})},bQa=function(a){g.lz("yt-remote-connected-devices",a,86400)},Q6=function(){if(P6)return P6;
var a=g.mz("yt-remote-device-id");a||(a=L6(),g.lz("yt-remote-device-id",a,31536E3));for(var b=O6(),c=1,d=a;g.jb(b,d);)c++,d=a+"#"+c;return P6=d},R6=function(){var a=O6(),b=Q6();
g.jb(a,b);g.pz()&&g.Bb(a,b);a=aQa(a);if(g.kb(a))try{g.qt("remote_sid")}catch(c){}else try{g.ot("remote_sid",a.join(","),-1)}catch(c){}},cQa=function(){return g.mz("yt-remote-session-browser-channel")},dQa=function(){return g.mz("yt-remote-local-screens")||[]},eQa=function(){g.lz("yt-remote-lounge-token-expiration",!0,86400)},fQa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Se(dQa(),function(d){return d.loungeToken}),c=g.Se(a,function(d){return d.loungeToken});
g.Fm(c,function(d){return!g.jb(b,d)})&&eQa();
g.lz("yt-remote-local-screens",a,31536E3)},gQa=function(a,b){g.lz("yt-remote-session-browser-channel",a);
g.lz("yt-remote-session-screen-id",b);a=O6();b=Q6();g.jb(a,b)||a.push(b);bQa(a);R6()},S6=function(a){a||(g.oz("yt-remote-session-screen-id"),g.oz("yt-remote-session-video-id"));
R6();a=O6();g.ob(a,Q6());bQa(a)},hQa=function(){if(!T6){var a=g.vr();
a&&(T6=new g.fr(a))}},iQa=function(){hQa();
return T6?!!T6.get("yt-remote-use-staging-server"):!1},U6=function(){var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);
return a?parseInt(a[1],10):0},jQa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},kQa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},V6=function(a){a.length?lQa(a.shift(),function(){V6(a)}):W6()},mQa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},lQa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.Fj(d,g.Al(a));(document.head||document.documentElement).appendChild(d)},nQa=function(){var a=U6(),b=[];
if(1<a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}return b},W6=function(){var a=kQa();
a&&a(!1,"No cast extension found")},X6=function(){if(oQa){var a=2,b=kQa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;lQa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",W6,c)}},pQa=function(){X6();
var a=nQa();a.push("//www.gstatic.com/eureka/clank/cast_sender.js");V6(a)},rQa=function(){X6();
var a=nQa();a.push.apply(a,g.la(qQa.map(mQa)));a.push("//www.gstatic.com/eureka/clank/cast_sender.js");V6(a)},Y6=function(a,b,c){g.E.call(this);
this.G=null!=c?(0,g.C)(a,c):a;this.Mf=b;this.C=(0,g.C)(this.AO,this);this.i=!1;this.l=0;this.u=this.Hb=null;this.B=[]},Z6=function(a,b,c){g.E.call(this);
this.B=null!=c?a.bind(c):a;this.Mf=b;this.u=null;this.i=!1;this.l=0;this.Hb=null},$6=function(a){a.Hb=g.nh(function(){a.Hb=null;
a.i&&!a.l&&(a.i=!1,$6(a))},a.Mf);
var b=a.u;a.u=null;a.B.apply(null,b)},a7=function(){},b7=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.B.setTimeout(function(){a()},b)},d7=function(a){c7.dispatchEvent(new sQa(c7,a))},sQa=function(a,b){g.mf.call(this,"statevent",a);
this.stat=b},e7=function(a,b,c,d){this.i=a;
this.l=b;this.L=c;this.J=d||1;this.C=45E3;this.B=new g.xk(this);this.u=new g.mh;this.u.setInterval(250)},uQa=function(a,b,c){a.Es=1;
a.zm=B6(b.clone());a.Up=c;a.G=!0;tQa(a,null)},f7=function(a,b,c,d,e){a.Es=1;
a.zm=B6(b.clone());a.Up=null;a.G=c;e&&(a.IL=!1);tQa(a,d)},tQa=function(a,b){a.rs=Date.now();
g7(a);a.On=a.zm.clone();C6(a.On,"t",a.J);a.zw=0;a.Ve=a.i.XB(a.i.bw()?b:null);0<a.QA&&(a.mz=new Z6((0,g.C)(a.HM,a,a.Ve),a.QA));a.B.Qa(a.Ve,"readystatechange",a.BO);b=a.Co?g.Wb(a.Co):{};a.Up?(a.bA="POST",b["Content-Type"]="application/x-www-form-urlencoded",a.Ve.send(a.On,a.bA,a.Up,b)):(a.bA="GET",a.IL&&!g.mg&&(b.Connection="close"),a.Ve.send(a.On,a.bA,null,b));a.i.nj(1)},xQa=function(a,b,c){for(var d=!0;!a.Po&&a.zw<c.length;){var e=vQa(a,c);
if(e==h7){4==b&&(a.tm=4,d7(15),d=!1);break}else if(e==wQa){a.tm=4;d7(16);d=!1;break}else i7(a,e)}4==b&&0==c.length&&(a.tm=1,d7(17),d=!1);a.Aj=a.Aj&&d;d||(j7(a),k7(a))},vQa=function(a,b){var c=a.zw,d=b.indexOf("\n",c);
if(-1==d)return h7;c=Number(b.substring(c,d));if(isNaN(c))return wQa;d+=1;if(d+c>b.length)return h7;b=b.substr(d,c);a.zw=d+c;return b},zQa=function(a,b){a.rs=Date.now();
g7(a);var c=b?window.location.hostname:"";a.On=a.zm.clone();g.rk(a.On,"DOMAIN",c);g.rk(a.On,"t",a.J);try{a.Ej=new ActiveXObject("htmlfile")}catch(m){j7(a);a.tm=7;d7(22);k7(a);return}var d="<html><body>";if(b){var e="";for(b=0;b<c.length;b++){var f=c.charAt(b);if("<"==f)f=e+"\\x3c";else if(">"==f)f=e+"\\x3e";else{if(f in l7)f=l7[f];else if(f in yQa)f=l7[f]=yQa[f];else{var h=f.charCodeAt(0);if(31<h&&127>h)var l=f;else{if(256>h){if(l="\\x",16>h||256<h)l+="0"}else l="\\u",4096>h&&(l+="0");l+=h.toString(16).toUpperCase()}f=
l7[f]=l}f=e+f}e=f}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.md(g.ic("b/12014412"),d);a.Ej.open();a.Ej.write(g.fd(c));a.Ej.close();a.Ej.parentWindow.m=(0,g.C)(a.MU,a);a.Ej.parentWindow.d=(0,g.C)(a.ZK,a,!0);a.Ej.parentWindow.rpcClose=(0,g.C)(a.ZK,a,!1);c=a.Ej.createElement("DIV");a.Ej.parentWindow.document.body.appendChild(c);d=g.Nc(a.On.toString());d=g.vd(g.Jc(d));d=g.md(g.ic("b/12014412"),'<iframe src="'+d+'"></iframe>');g.od(c,d);a.i.nj(1)},g7=function(a){a.uF=Date.now()+
a.C;
AQa(a,a.C)},AQa=function(a,b){if(null!=a.Ls)throw Error("WatchDog timer not null");
a.Ls=b7((0,g.C)(a.TU,a),b)},m7=function(a){a.Ls&&(g.B.clearTimeout(a.Ls),a.Ls=null)},k7=function(a){a.i.df()||a.Po||a.i.Lw(a)},j7=function(a){m7(a);
g.jf(a.mz);a.mz=null;a.u.stop();g.zk(a.B);if(a.Ve){var b=a.Ve;a.Ve=null;b.abort();b.dispose()}a.Ej&&(a.Ej=null)},i7=function(a,b){try{a.i.SK(a,b),a.i.nj(4)}catch(c){}},CQa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;BQa(a,b,function(h){h?c(!0):g.B.setTimeout(function(){CQa(a,b,c,d,f)},f)})}},BQa=function(a,b,c){var d=new Image;
d.onload=function(){try{n7(d),c(!0)}catch(e){}};
d.onerror=function(){try{n7(d),c(!1)}catch(e){}};
d.onabort=function(){try{n7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{n7(d),c(!1)}catch(e){}};
g.B.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
KPa(d,a)},n7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},DQa=function(a){this.i=a;
this.l=new a7},EQa=function(a){var b=o7(a.i,a.Gt,"/mail/images/cleardot.gif");
B6(b);CQa(b.toString(),5E3,(0,g.C)(a.vP,a),3,2E3);a.nj(1)},q7=function(a){var b=a.i.L;
if(null!=b)d7(5),b?(d7(11),p7(a.i,a,!1)):(d7(12),p7(a.i,a,!0));else if(a.gh=new e7(a,void 0,void 0,void 0),a.gh.Co=a.RA,b=a.i,b=o7(b,b.bw()?a.ut:null,a.SA),d7(5),!g.ie||g.ce(10))C6(b,"TYPE","xmlhttp"),f7(a.gh,b,!1,a.ut,!1);else{C6(b,"TYPE","html");var c=a.gh;a=!!a.ut;c.Es=3;c.zm=B6(b.clone());zQa(c,a)}},r7=function(a,b,c){this.Pa=1;
this.i=[];this.u=[];this.B=new a7;this.J=a||null;this.L=null!=b?b:null;this.C=c||!1},FQa=function(a,b){this.i=a;
this.map=b;this.context=null},GQa=function(a,b,c,d){g.mf.call(this,"timingevent",a);
this.size=b;this.Tv=d},HQa=function(a){g.mf.call(this,"serverreachability",a)},KQa=function(a){IQa(a);
if(3==a.Pa){var b=a.Zu++,c=a.ox.clone();g.rk(c,"SID",a.l);g.rk(c,"RID",b);g.rk(c,"TYPE","terminate");s7(a,c);b=new e7(a,a.l,b,void 0);b.Es=2;b.zm=B6(c.clone());KPa(new Image,b.zm.toString());b.rs=Date.now();g7(b)}JQa(a)},LQa=function(a){a.WP(1,0);
a.ox=o7(a,null,a.TA);t7(a)},IQa=function(a){a.Em&&(a.Em.abort(),a.Em=null);
a.ze&&(a.ze.cancel(),a.ze=null);a.ql&&(g.B.clearTimeout(a.ql),a.ql=null);u7(a);a.Ng&&(a.Ng.cancel(),a.Ng=null);a.Lm&&(g.B.clearTimeout(a.Lm),a.Lm=null)},MQa=function(a,b){if(0==a.Pa)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new FQa(a.ER++,b));2!=a.Pa&&3!=a.Pa||t7(a)},NQa=function(a){var b=0;
a.ze&&b++;a.Ng&&b++;return b},t7=function(a){a.Ng||a.Lm||(a.Lm=b7((0,g.C)(a.XK,a),0),a.xr=0)},PQa=function(a,b){if(1==a.Pa){if(!b){a.Zu=Math.floor(1E5*Math.random());
b=a.Zu++;var c=new e7(a,"",b,void 0);c.Co=a.Sj;var d=v7(a),e=a.ox.clone();g.rk(e,"RID",b);g.rk(e,"CVER","1");s7(a,e);uQa(c,e,d);a.Ng=c;a.Pa=2}}else 3==a.Pa&&(b?OQa(a,b):0==a.i.length||a.Ng||OQa(a))},OQa=function(a,b){if(b)if(6<a.Qo){a.i=a.u.concat(a.i);
a.u.length=0;var c=a.Zu-1;b=v7(a)}else c=b.L,b=b.Up;else c=a.Zu++,b=v7(a);var d=a.ox.clone();g.rk(d,"SID",a.l);g.rk(d,"RID",c);g.rk(d,"AID",a.Or);s7(a,d);c=new e7(a,a.l,c,a.xr+1);c.Co=a.Sj;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Ng=c;uQa(c,d,b)},s7=function(a,b){a.Hf&&(a=a.Hf.wI())&&g.Eb(a,function(c,d){g.rk(b,d,c)})},v7=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Qo&&0<b){var d=a.i[0].i;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={yq:e.yq},f++){e.yq=a.i[f].i;var h=a.i[f].map;e.yq=6>=a.Qo?f:e.yq-d;try{g.Eb(h,function(l){return function(m,n){c.push("req"+l.yq+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.yq+"_type="+encodeURIComponent("_badmap"))}}a.u=a.u.concat(a.i.splice(0,b));
return c.join("&")},QQa=function(a){a.ze||a.ql||(a.G=1,a.ql=b7((0,g.C)(a.WK,a),0),a.Vq=0)},w7=function(a){if(a.ze||a.ql||3<=a.Vq)return!1;
a.G++;a.ql=b7((0,g.C)(a.WK,a),RQa(a,a.Vq));a.Vq++;return!0},p7=function(a,b,c){a.Zz=c;
a.Tj=b.Sk;a.C||LQa(a)},u7=function(a){null!=a.Yo&&(g.B.clearTimeout(a.Yo),a.Yo=null)},RQa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},x7=function(a,b){if(2==b||9==b){var c=null;
a.Hf&&(c=null);var d=(0,g.C)(a.OV,a);c||(c=new g.fk("//www.google.com/images/cleardot.gif"),B6(c));BQa(c.toString(),1E4,d)}else d7(2);SQa(a,b)},SQa=function(a,b){a.Pa=0;
a.Hf&&a.Hf.MH(b);JQa(a);IQa(a)},JQa=function(a){a.Pa=0;
a.Tj=-1;if(a.Hf)if(0==a.u.length&&0==a.i.length)a.Hf.KB();else{g.rb(a.u);var b=g.rb(a.i);a.u.length=0;a.i.length=0;a.Hf.KB(b)}},o7=function(a,b,c){var d=g.sk(c);
if(""!=d.i)b&&g.hk(d,b+"."+d.i),g.ik(d,d.u);else{var e=window.location;d=SPa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Yt&&g.Eb(a.Yt,function(f,h){g.rk(d,h,f)});
g.rk(d,"VER",a.Qo);s7(a,d);return d},TQa=function(){},UQa=function(){this.i=[];
this.l=[]},VQa=function(a,b){this.action=a;
this.params=b||{}},y7=function(a,b){g.E.call(this);
this.i=new g.J(this.EU,0,this);g.F(this,this.i);this.Mf=5E3;this.l=0;if("function"===typeof a)b&&(a=(0,g.C)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.C)(a.handleEvent,a);else throw Error("Invalid listener argument");this.u=a},z7=function(a,b,c,d,e){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
e=void 0===e?!1:e;this.xa=a;this.G=b;this.u=new g.er;this.l=new y7(this.tV,this);this.i=null;this.ea=!1;this.C=null;this.V="";this.L=this.B=0;this.J=[];this.ya=c;this.X=d;this.Aa=e},WQa=function(a){return{firstTestResults:[""],
secondTestResults:!a.i.Zz,sessionId:a.i.l,arrayId:a.i.Or}},XQa=function(a,b){a.L=b||0;
a.l.stop();A7(a);a.i&&(3==a.i.getState()&&PQa(a.i),KQa(a.i));a.L=0},B7=function(a){return!!a.i&&3==a.i.getState()},A7=function(a){if(a.i){var b=a.X(),c=a.i.Sj||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.i.Sj=c}},C7=function(a){this.port=this.domain="";
this.i="/api/lounge";this.l=!0;a=a||document.location.href;var b=Number(g.ki(4,a))||"";b&&(this.port=":"+b);this.domain=g.li(a)||"";a=g.Xc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Gc(a,"10.0")&&(this.l=!1))},D7=function(a,b){var c=a.i;
a.l&&(c="https://"+a.domain+a.port+a.i);return g.wi(c+b,{})},E7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Pa(a.B,d,!0),onError:g.Pa(a.u,e),onTimeout:g.Pa(a.C,e)};c&&(a.postParams=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.dt(b,a)},aRa=function(){var a=YQa;
ZQa();F7.push(a);$Qa()},G7=function(a,b){ZQa();
var c=bRa(a,String(b));g.kb(F7)?cRa(c):($Qa(),g.Cb(F7,function(d){d(c)}))},ZQa=function(){F7||(F7=g.Ha("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",F7,void 0))},cRa=function(a){var b=(H7+1)%50;
H7=b;I7[b]=a;J7||(J7=49==b)},$Qa=function(){var a=F7;
if(I7[0]){var b=J7?H7:-1;do{b=(b+1)%50;var c=I7[b];g.Cb(a,function(d){d(c)})}while(b!=H7);
I7=Array(50);H7=-1;J7=!1}},bRa=function(a,b){var c=(Date.now()-dRa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},K7=function(a){g.P.call(this);
this.G=a;this.screens=[]},eRa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c)return a=c.name,c.id=b.id||c.id,c.name=b.name,c.token=b.token,c.uuid=b.uuid||c.uuid,c.name!=a;a.screens.push(b);return!0},fRa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.To(a.screens,function(f){return!!M6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=eRa(a,b[d])||c;return c},gRa=function(a,b){var c=a.screens.length;
a.screens=g.To(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},L7=function(a,b,c,d,e){g.P.call(this);
this.u=a;this.J=b;this.B=c;this.G=d;this.C=e;this.l=0;this.i=null;this.Hb=NaN},N7=function(a){K7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;M7(this);this.info("Initializing with "+K6(this.screens))},hRa=function(a){if(a.screens.length){var b=g.Se(a.screens,function(d){return d.id}),c=D7(a.l,"/pairing/get_lounge_token_batch");
E7(a.l,c,{screen_ids:b.join(",")},(0,g.C)(a.vQ,a),(0,g.C)(a.uQ,a))}},M7=function(a){if(g.as("deprecate_pair_servlet_enabled"))return fRa(a,[]);
var b=YPa(dQa());b=g.To(b,function(c){return!c.uuid});
return fRa(a,b)},O7=function(a,b){fQa(g.Se(a.screens,WPa));
b&&eQa()},Q7=function(a,b){g.P.call(this);
this.G=b;b=(b=g.mz("yt-remote-online-screen-ids")||"")?b.split(","):[];for(var c={},d=this.G(),e=0,f=d.length;e<f;++e){var h=d[e].id;c[h]=g.jb(b,h)}this.i=c;this.C=a;this.u=this.B=NaN;this.l=null;P7("Initialized with "+g.Qh(this.i))},R7=function(a,b,c){var d=D7(a.C,"/pairing/get_screen_availability");
E7(a.C,d,{lounge_token:b.token},(0,g.C)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.C)(function(){c(!1)},a))},S7=function(a,b){a:if(D6(b)!=D6(a.i))var c=!1;
else{c=g.Mb(b);for(var d=0,e=c.length;d<e;++d)if(!a.i[c[d]]){c=!1;break a}c=!0}c||(P7("Updated online screens: "+g.Qh(a.i)),a.i=b,a.Z("screenChange"));iRa(a)},T7=function(a){isNaN(a.u)||g.Zs(a.u);
a.u=g.Xs((0,g.C)(a.qE,a),0<a.B&&a.B<g.Ra()?2E4:1E4)},P7=function(a){G7("OnlineScreenService",a)},jRa=function(a){var b={};
g.Cb(a.G(),function(c){c.token?b[c.token]=c.id:this.Wd("Requesting availability of screen w/o lounge token.")});
return b},iRa=function(a){a=g.Mb(g.Fb(a.i,function(b){return b}));
g.zb(a);a.length?g.lz("yt-remote-online-screen-ids",a.join(","),60):g.oz("yt-remote-online-screen-ids")},U7=function(a,b){b=void 0===b?!1:b;
K7.call(this,"ScreenService");this.B=a;this.J=b;this.i=this.l=null;this.u=[];this.C={};kRa(this)},mRa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.C[b]);var h=a.Bh(),l=c?N6(h,c):null;c&&(a.J||l)||(l=N6(h,b));if(l){l.uuid=b;var m=V7(a,l);R7(a.i,m,function(n){e(n?m:null)})}else c?lRa(a,c,(0,g.C)(function(n){var p=V7(this,new H6({name:d,
screenId:c,loungeToken:n,dialId:b||""}));R7(this.i,p,function(r){e(r?p:null)})},a),f):e(null)},nRa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},oRa=function(a,b,c){R7(a.i,b,c)},lRa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={postParams:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){f=h&&h.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.dt(D7(a.B,"/pairing/get_lounge_token_batch"),e)},pRa=function(a){a.screens=a.l.Bh();
var b=a.C,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+K6(a.screens))},kRa=function(a){W7(a);
a.l=new N7(a.B);a.l.subscribe("screenChange",(0,g.C)(a.EQ,a));pRa(a);a.J||(a.u=YPa(g.mz("yt-remote-automatic-screen-cache")||[]));W7(a);a.info("Initializing automatic screens: "+K6(a.u));a.i=new Q7(a.B,(0,g.C)(a.Bh,a,!0));a.i.subscribe("screenChange",(0,g.C)(function(){this.Z("onlineScreenChange")},a))},V7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=N6(a.u,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.u.push(b),a.J||qRa(a));W7(a);a.C[b.uuid]=b.id;g.lz("yt-remote-device-id-map",a.C,31536E3);return b},qRa=function(a){a=g.To(a.u,function(b){return"shortLived"!=b.idType});
g.lz("yt-remote-automatic-screen-cache",g.Se(a,WPa))},W7=function(a){a.C=g.mz("yt-remote-device-id-map")||{}},X7=function(a,b,c){g.P.call(this);
this.Aa=c;this.u=a;this.i=b;this.B=null},Y7=function(a,b){a.B=b;
a.Z("sessionScreen",a.B)},rRa=function(a,b){a.B&&(a.B.token=b,V7(a.u,a.B));
a.Z("sessionScreen",a.B)},Z7=function(a,b){G7(a.Aa,b)},$7=function(a,b,c){X7.call(this,a,b,"CastSession");
var d=this;this.config_=c;this.l=null;this.X=(0,g.C)(this.GO,this);this.ya=(0,g.C)(this.WU,this);this.ea=g.Xs(function(){sRa(d,null)},12E4);
this.J=this.C=this.G=this.L=0;this.xa=!1;this.V="unknown"},a8=function(a,b){g.Zs(a.J);
a.J=0;0==b?tRa(a):a.J=g.Xs(function(){tRa(a)},b)},tRa=function(a){uRa(a,"getLoungeToken");
g.Zs(a.C);a.C=g.Xs(function(){vRa(a,null)},3E4)},uRa=function(a,b){a.info("sendYoutubeMessage_: "+b+" "+g.Qh(void 0));
var c={};c.type=b;a.l?a.l.sendMessage("urn:x-cast:com.google.youtube.mdx",c,g.Ia,(0,g.C)(function(){Z7(this,"Failed to send message: "+b+".")},a)):Z7(a,"Sending yt message without session: "+g.Qh(c))},b8=function(a,b){b?(a.info("onConnectedScreenId_: Received screenId: "+b),a.getScreen()&&a.getScreen().id==b||a.LI(b,function(c){Y7(a,c)},function(){return a.fg()},5)):a.fg(Error("Waiting for session status timed out."))},xRa=function(a,b,c){a.info("onConnectedScreenData_: Received screenData: "+JSON.stringify(b));
var d=new H6(b);wRa(a,d,function(e){e?(a.xa=!0,V7(a.u,d),Y7(a,d),a.V="unknown",a8(a,c)):(g.fs(Error("CastSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online.")),a.fg())},5)},sRa=function(a,b){g.Zs(a.ea);
a.ea=0;b?a.config_.enableCastLoungeToken&&b.loungeToken?b.deviceId?a.getScreen()&&a.getScreen().uuid==b.deviceId||(b.loungeTokenRefreshIntervalMs?xRa(a,{name:a.i.friendlyName,screenId:b.screenId,loungeToken:b.loungeToken,dialId:b.deviceId,screenIdType:"shortLived"},b.loungeTokenRefreshIntervalMs):(g.fs(Error("No loungeTokenRefreshIntervalMs presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),b8(a,b.screenId))):(g.fs(Error("No device id presents in mdxSessionStatusData: "+JSON.stringify(b)+
".")),b8(a,b.screenId)):b8(a,b.screenId):a.fg(Error("Waiting for session status timed out."))},vRa=function(a,b){g.Zs(a.C);
a.C=0;var c=null;if(b)if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";else c="noLoungeTokenResponse";c?(a.info("Did not receive a new lounge token in onLoungeToken_ with data: "+(JSON.stringify(b)+", error: "+c)),a.V=c,a8(a,3E4)):(rRa(a,b.loungeToken),a.xa=!1,a.V="unknown",a8(a,b.loungeTokenRefreshIntervalMs))},wRa=function(a,b,c,d){g.Zs(a.G);
a.G=0;oRa(a.u,b,function(e){e||0>d?c(e):a.G=g.Xs(function(){wRa(a,b,c,d-1)},300)})},yRa=function(a){g.Zs(a.L);
a.L=0;g.Zs(a.G);a.G=0;g.Zs(a.ea);a.ea=0;g.Zs(a.C);a.C=0;g.Zs(a.J);a.J=0},c8=function(a,b,c,d){X7.call(this,a,b,"DialSession");
this.config_=d;this.l=this.L=null;this.ya="";this.Ia=c;this.Ja=null;this.ea=g.Ia;this.V=NaN;this.Da=(0,g.C)(this.HO,this);this.C=g.Ia;this.J=this.G=0;this.X=!1;this.xa="unknown"},d8=function(a){var b;
return!!(a.config_.enableDialLoungeToken&&(null==(b=a.l)?0:b.getDialAppInfo))},zRa=function(a){a.C=a.u.pG(a.ya,a.i.label,a.i.friendlyName,d8(a),function(b,c){a.C=g.Ia;
a.X=!0;Y7(a,b);"shortLived"==b.idType&&0<c&&e8(a,c)},function(b){a.C=g.Ia;
a.fg(b)})},ARa=function(a){var b={};
b.pairingCode=a.ya;b.theme=a.Ia;iQa()&&(b.env_useStageMdx=1);return g.ui(b)},f8=function(a){return new Promise(function(b){a.ya=L6();
if(a.Ja){var c=new chrome.cast.DialLaunchResponse(!0,ARa(a));b(c);zRa(a)}else a.ea=function(){g.Zs(a.V);a.ea=function(){};
a.V=NaN;var d=new chrome.cast.DialLaunchResponse(!0,ARa(a));b(d);zRa(a)},a.V=g.Xs(function(){a.ea()},100)})},CRa=function(a,b,c){a.info("initOnConnectedScreenDataPromise_: Received screenData: "+JSON.stringify(b));
var d=new H6(b);return(new Promise(function(e){BRa(a,d,function(f){f?(a.X=!0,V7(a.u,d),Y7(a,d),e8(a,c)):g.fs(Error("DialSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online."));e(f)},5)})).then(function(e){return e?new chrome.cast.DialLaunchResponse(!1):f8(a)})},DRa=function(a,b){var c=a.L.receiver.label,d=a.i.friendlyName;
return(new Promise(function(e){mRa(a.u,c,b,d,function(f){f&&f.token&&Y7(a,f);e(f)},function(f){Z7(a,"Failed to get DIAL screen: "+f);
e(null)})})).then(function(e){return e&&e.token?new chrome.cast.DialLaunchResponse(!1):f8(a)})},BRa=function(a,b,c,d){g.Zs(a.G);
a.G=0;oRa(a.u,b,function(e){e||0>d?c(e):a.G=g.Xs(function(){BRa(a,b,c,d-1)},300)})},e8=function(a,b){a.info("getDialAppInfoWithTimeout_ "+b);
d8(a)&&(g.Zs(a.J),a.J=0,0==b?ERa(a):a.J=g.Xs(function(){ERa(a)},b))},ERa=function(a){d8(a)&&a.l.getDialAppInfo(function(b){a.info("getDialAppInfo dialLaunchData: "+JSON.stringify(b));
b=b.extraData||{};var c=null;if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";c?(a.xa=c,e8(a,3E4)):(a.X=!1,a.xa="unknown",rRa(a,b.loungeToken),e8(a,b.loungeTokenRefreshIntervalMs))},function(b){a.info("getDialAppInfo error: "+b);
a.xa="noLoungeTokenResponse";e8(a,3E4)})},FRa=function(a){g.Zs(a.G);
a.G=0;g.Zs(a.J);a.J=0;a.C();a.C=function(){};
g.Zs(a.V)},g8=function(a,b){X7.call(this,a,b,"ManualSession");
this.l=g.Xs((0,g.C)(this.Pr,this,null),150)},h8=function(a,b){g.P.call(this);
this.config_=b;this.l=a;this.J=b.appId||"233637DE";this.B=b.theme||"cl";this.L=b.disableCastApi||!1;this.V=b.forceMirroring||!1;this.i=null;this.G=!1;this.u=[];this.C=(0,g.C)(this.PT,this)},GRa=function(a,b){return b?g.fb(a.u,function(c){return I6(b,c.label)},a):null},i8=function(a){G7("Controller",a)},YQa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},j8=function(a){return a.G||!!a.u.length||!!a.i},k8=function(a,b,c){b!=a.i&&(g.jf(a.i),(a.i=b)?(c?a.Z("yt-remote-cast2-receiver-resumed",
b.i):a.Z("yt-remote-cast2-receiver-selected",b.i),b.subscribe("sessionScreen",(0,g.C)(a.VK,a,b)),b.subscribe("sessionFailed",function(){return HRa(a,b)}),b.getScreen()?a.Z("yt-remote-cast2-session-change",b.getScreen()):c&&a.i.Pr(null)):a.Z("yt-remote-cast2-session-change",null))},HRa=function(a,b){a.i==b&&a.Z("yt-remote-cast2-session-failed")},IRa=function(a){var b=a.l.oG(),c=a.i&&a.i.i;
a=g.Se(b,function(d){c&&I6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=GRa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},NRa=function(a,b,c,d){d.disableCastApi?l8("Cannot initialize because disabled by Mdx config."):JRa()?KRa(b,d)&&(m8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?LRa(a,c):(window.__onGCastApiAvailable=function(e,f){e?LRa(a,c):(n8("Failed to load cast API: "+f),o8(!1),m8(!1),g.oz("yt-remote-cast-available"),g.oz("yt-remote-cast-receiver"),
MRa(),c(!1))},d.loadCastApiSetupScript?g.qz("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?60<=U6()&&pQa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?W6():89<=U6()?rQa():(X6(),V6(qQa.map(mQa))))):l8("Cannot initialize because not running Chrome")},MRa=function(){l8("dispose");
var a=p8();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);ORa(!1);g.Mu(q8);q8.length=0},r8=function(){return!!g.mz("yt-remote-cast-installed")},PRa=function(){var a=g.mz("yt-remote-cast-receiver");
return a?a.friendlyName:null},QRa=function(){l8("clearCurrentReceiver");
g.oz("yt-remote-cast-receiver")},RRa=function(){return r8()?p8()?p8().getCastSession():(n8("getCastSelector: Cast is not initialized."),null):(n8("getCastSelector: Cast API is not installed!"),null)},t8=function(){r8()?p8()?s8()?(l8("Requesting cast selector."),p8().requestSession()):(l8("Wait for cast API to be ready to request the session."),q8.push(g.Lu("yt-remote-cast2-api-ready",t8))):n8("requestCastSelector: Cast is not initialized."):n8("requestCastSelector: Cast API is not installed!")},u8=
function(a,b){s8()?p8().setConnectedScreenStatus(a,b):n8("setConnectedScreenStatus called before ready.")},JRa=function(){var a=0<=g.Xc.search(/ (CrMo|Chrome|CriOS)\//);
return g.ej||a},SRa=function(a,b){p8().init(a,b)},KRa=function(a,b){var c=!1;
p8()||(a=new h8(a,b),a.subscribe("yt-remote-cast2-availability-change",function(d){g.lz("yt-remote-cast-available",d);F6("yt-remote-cast2-availability-change",d)}),a.subscribe("yt-remote-cast2-receiver-selected",function(d){l8("onReceiverSelected: "+d.friendlyName);
g.lz("yt-remote-cast-receiver",d);F6("yt-remote-cast2-receiver-selected",d)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(d){l8("onReceiverResumed: "+d.friendlyName);
g.lz("yt-remote-cast-receiver",d);F6("yt-remote-cast2-receiver-resumed",d)}),a.subscribe("yt-remote-cast2-session-change",function(d){l8("onSessionChange: "+J6(d));
d||g.oz("yt-remote-cast-receiver");F6("yt-remote-cast2-session-change",d)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),c=!0);
l8("cloudview.createSingleton_: "+c);return c},p8=function(){return g.Ha("yt.mdx.remote.cloudview.instance_")},LRa=function(a,b){o8(!0);
m8(!1);SRa(a,function(c){c?(ORa(!0),g.Nu("yt-remote-cast2-api-ready")):(n8("Failed to initialize cast API."),o8(!1),g.oz("yt-remote-cast-available"),g.oz("yt-remote-cast-receiver"),MRa());b(c)})},l8=function(a){G7("cloudview",a)},n8=function(a){G7("cloudview",a)},o8=function(a){l8("setCastInstalled_ "+a);
g.lz("yt-remote-cast-installed",a)},s8=function(){return!!g.Ha("yt.mdx.remote.cloudview.apiReady_")},ORa=function(a){l8("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},m8=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},v8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.G=this.J=0;this.trackData=null;this.hasNext=this.nk=!1;this.L=this.C=this.i=this.B=0;this.u=NaN;this.l=!1;this.reset(a)},w8=function(a){a.audioTrackId=null;
a.trackData=null;a.playerState=-1;a.nk=!1;a.hasNext=!1;a.J=0;a.G=g.Ra();a.B=0;a.i=0;a.C=0;a.L=0;a.u=NaN;a.l=!1},x8=function(a){return a.xc()?(g.Ra()-a.G)/1E3:0},y8=function(a,b){a.J=b;
a.G=g.Ra()},z8=function(a){switch(a.playerState){case 1:case 1081:return(g.Ra()-a.G)/1E3+a.J;
case -1E3:return 0}return a.J},A8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&w8(a)},B8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Xb(a.trackData);b.hasPrevious=a.nk;b.hasNext=a.hasNext;b.playerTime=a.J;b.playerTimeAt=a.G;b.seekableStart=a.B;b.seekableEnd=a.i;b.duration=a.C;b.loadedTime=a.L;b.liveIngestionTime=a.u;return b},D8=function(a,b){g.P.call(this);
this.Pa=0;this.u=a;this.C=[];this.B=new UQa;this.l=this.i=null;this.L=(0,g.C)(this.oS,this);this.G=(0,g.C)(this.vv,this);this.J=(0,g.C)(this.nS,this);this.V=(0,g.C)(this.wS,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.FE,this),TRa(this))):c=3;0!=c&&(b?this.FE(c):g.Xs((0,g.C)(function(){this.FE(c)},this),0));
(a=RRa())&&C8(this,a);this.subscribe("yt-remote-cast2-session-change",this.V)},E8=function(a){return new v8(a.u.getPlayerContextData())},TRa=function(a){g.Cb("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange multiStateLoopEnabled".split(" "),function(b){this.C.push(this.u.subscribe(b,g.Pa(this.LT,b),this))},a)},URa=function(a){g.Cb(a.C,function(b){this.u.unsubscribeByKey(b)},a);
a.C.length=0},F8=function(a){return 1==a.getState()},G8=function(a,b){var c=a.B;
50>c.i.length+c.l.length&&a.B.l.push(b)},I8=function(a,b,c){var d=E8(a);
y8(d,c);-1E3!=d.playerState&&(d.playerState=b);H8(a,d)},J8=function(a,b,c){a.u.sendMessage(b,c)},H8=function(a,b){URa(a);
a.u.setPlayerContextData(B8(b));TRa(a)},C8=function(a,b){a.l&&(a.l.removeUpdateListener(a.L),a.l.removeMediaListener(a.G),a.vv(null));
a.l=b;a.l&&(G7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.L),a.l.addMediaListener(a.G),a.l.media.length&&a.vv(a.l.media[0]))},VRa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=E8(a);b.contentId!=d.videoId&&G7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;y8(d,a.i.getEstimatedTime());H8(a,d)}else G7("CP","No cast media video. Ignoring state update.")},K8=function(a,b,c){return(0,g.C)(function(d){this.Wd("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Wd("Retrying "+b+" using MDx browser channel."),J8(this,b,c))},a)},L8=function(a,b,c){g.P.call(this);
this.C=NaN;this.xa=!1;this.L=this.J=this.ea=this.X=NaN;this.V=[];this.B=this.G=this.u=this.hc=this.i=null;this.Aa=a;this.V.push(g.cu(window,"beforeunload",(0,g.C)(this.qQ,this)));this.l=[];this.hc=new v8;this.Da=b.id;this.ya=b.idType;this.i=WRa(this,c);this.i.subscribe("handlerOpened",this.tS,this);this.i.subscribe("handlerClosed",this.pS,this);this.i.subscribe("handlerError",this.qS,this);this.i.subscribe("handlerMessage",this.sS,this);this.i.Bz(b.token);this.subscribe("remoteQueueChange",function(){var d=
this.hc.videoId;g.pz()&&g.lz("yt-remote-session-video-id",d)},this)},XRa=function(a){return g.fb(a.l,function(b){return"LOUNGE_SCREEN"==b.type})},M8=function(a){G7("conn",a)},WRa=function(a,b){return new z7(D7(a.Aa,"/bc"),b,!1,function(){return a.tG()},"shortLived"==a.ya)},N8=function(a,b){a.Z("proxyStateChange",b)},YRa=function(a){a.C=g.Xs((0,g.C)(function(){M8("Connecting timeout");
this.qr(1)},a),2E4)},O8=function(a){g.Zs(a.C);
a.C=NaN},P8=function(a){g.Zs(a.X);
a.X=NaN},ZRa=function(a){Q8(a);
a.ea=g.Xs((0,g.C)(function(){R8(this,"getNowPlaying")},a),2E4)},Q8=function(a){g.Zs(a.ea);
a.ea=NaN},aSa=function(a,b){var c=null;
if(b){var d=XRa(a);d&&(c={clientName:d.clientName,deviceMake:d.brand,deviceModel:d.model,osVersion:d.osVersion})}g.Ga("yt.mdx.remote.remoteClient_",c,void 0);b&&(O8(a),P8(a));c=B7(a.i)&&isNaN(a.C);b==c?b&&(N8(a,1),R8(a,"getSubtitlesTrack")):b?(a.KI()&&a.hc.reset(),N8(a,1),R8(a,"getNowPlaying"),$Ra(a)):a.qr(1)},bSa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.hc.videoId&&(g.Sb(b.params)?a.hc.trackData=null:a.hc.trackData=b.params,a.Z("remotePlayerChange"))},cSa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.hc.listId=b.params.listId||a.hc.listId;A8(a.hc,c,d);a.Z("remoteQueueChange")},eSa=function(a,b){b.params=b.params||{};
cSa(a,b);dSa(a,b);a.Z("autoplayDismissed")},dSa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
y8(a.hc,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.hc.playerState&&(c=-1E3);a.hc.playerState=c;c=Number(b.params.loadedTime);a.hc.L=isNaN(c)?0:c;a.hc.yj(Number(b.params.duration));c=a.hc;var d=Number(b.params.liveIngestionTime);c.u=d;c.l=isNaN(d)?!1:!0;c=a.hc;d=Number(b.params.seekableStartTime);b=Number(b.params.seekableEndTime);c.B=isNaN(d)?0:d;c.i=isNaN(b)?0:b;1==a.hc.playerState?ZRa(a):Q8(a);a.Z("remotePlayerChange")},fSa=function(a,b){if(-1E3!=a.hc.playerState){var c=
1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.hc.playerState=c;b=parseInt(b.params.currentTime,10);y8(a.hc,isNaN(b)?0:b);a.Z("remotePlayerChange")}},gSa=function(a,b){var c="true"==b.params.muted;
a.hc.volume=parseInt(b.params.volume,10);a.hc.muted=c;a.Z("remotePlayerChange")},hSa=function(a,b){a.G=b.params.videoId;
a.Z("nowAutoplaying",parseInt(b.params.timeout,10))},iSa=function(a,b){var c="true"==b.params.hasNext;
a.hc.nk="true"==b.params.hasPrevious;a.hc.hasNext=c;a.Z("previousNextChange")},$Ra=function(a){g.Zs(a.L);
a.L=g.Xs((0,g.C)(a.qr,a,1),864E5)},R8=function(a,b,c){c?M8("Sending: action="+b+", params="+g.Qh(c)):M8("Sending: action="+b);
a.i.sendMessage(b,c)},S8=function(a){K7.call(this,"ScreenServiceProxy");
this.He=a;this.i=[];this.i.push(this.He.$_s("screenChange",(0,g.C)(this.LO,this)));this.i.push(this.He.$_s("onlineScreenChange",(0,g.C)(this.tT,this)))},mSa=function(a,b){hQa();
if(!T6||!T6.get("yt-remote-disable-remote-module-for-dev")){b=g.N("MDX_CONFIG")||b;$Pa();R6();T8||(T8=new C7(b?b.loungeApiHost:void 0),iQa()&&(T8.i="/api/loungedev"));U8||(U8=g.Ha("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",U8,void 0));jSa();var c=V8();if(!c){var d=new U7(T8,b?b.disableAutomaticScreenCache||!1:!1);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=V8();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,
disableCastApi:b.disableCastApi,enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken,forceMirroring:b.forceMirroring});NRa(a,d,function(f){f?W8()&&u8(W8(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){F6("yt-remote-receiver-availability-change")})},e)}b&&!g.Ha("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),X8("Initializing: "+g.Qh(b)),Y8.push(g.Lu("yt-remote-cast2-availability-change",function(){F6("yt-remote-receiver-availability-change")})),
Y8.push(g.Lu("yt-remote-cast2-receiver-selected",function(){Z8(null);
F6("yt-remote-auto-connect","cast-selector-receiver")})),Y8.push(g.Lu("yt-remote-cast2-receiver-resumed",function(){F6("yt-remote-receiver-resumed","cast-selector-receiver")})),Y8.push(g.Lu("yt-remote-cast2-session-change",kSa)),Y8.push(g.Lu("yt-remote-connection-change",function(f){f?u8(W8(),"YouTube TV"):$8()||(u8(null,null),QRa())})),Y8.push(g.Lu("yt-remote-cast2-session-failed",function(){F6("yt-remote-connection-failed")})),a=a9(),b.isAuto&&(a.id+="#dial"),e=b.capabilities||[],g.as("desktop_enable_autoplay")&&
e.push("atp"),0<e.length&&(a.capabilities=e),a.name=b.device,a.app=b.app,(b=b.theme)&&(a.theme=b),X8(" -- with channel params: "+g.Qh(a)),a?(g.lz("yt-remote-session-app",a.app),g.lz("yt-remote-session-name",a.name)):(g.oz("yt-remote-session-app"),g.oz("yt-remote-session-name")),g.Ga("yt.mdx.remote.channelParams_",a,void 0),c.start(),W8()||lSa())}},nSa=function(){var a=V8().He.$_gos();
var b=b9();b&&c9()&&(M6(a,b)||a.push(b));return ZPa(a)},d9=function(){var a=oSa();
!a&&r8()&&PRa()&&(a={key:"cast-selector-receiver",name:PRa()});return a},oSa=function(){var a=nSa(),b=b9();
b||(b=$8());return g.fb(a,function(c){return b&&I6(b,c.key)?!0:!1})},b9=function(){var a=W8();
if(!a)return null;var b=V8().Bh();return N6(b,a)},kSa=function(a){X8("remote.onCastSessionChange_: "+J6(a));
if(a){var b=b9();if(b&&b.id==a.id){if(u8(b.id,"YouTube TV"),"shortLived"==a.idType&&(a=a.token))e9&&(e9.token=a),(b=c9())&&b.Bz(a)}else b&&f9(),g9(a,1)}else c9()&&f9()},f9=function(){s8()?p8().stopSession():n8("stopSession called before API ready.");
var a=c9();a&&(a.disconnect(1),h9(null))},i9=function(){var a=c9();
return!!a&&3!=a.getProxyState()},X8=function(a){G7("remote",a)},V8=function(){if(!j9){var a=g.Ha("yt.mdx.remote.screenService_");
j9=a?new S8(a):null}return j9},W8=function(){return g.Ha("yt.mdx.remote.currentScreenId_")},pSa=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},qSa=function(){return g.Ha("yt.mdx.remote.connectData_")},Z8=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},c9=function(){return g.Ha("yt.mdx.remote.connection_")},h9=function(a){var b=c9();
Z8(null);a||pSa("");g.Ga("yt.mdx.remote.connection_",a,void 0);U8&&(g.Cb(U8,function(c){c(a)}),U8.length=0);
b&&!a?F6("yt-remote-connection-change",!1):!b&&a&&F6("yt-remote-connection-change",!0)},$8=function(){var a=g.pz();
if(!a)return null;var b=V8();if(!b)return null;b=b.Bh();return N6(b,a)},g9=function(a,b){W8();
b9()&&b9();k9?e9=a:(pSa(a.id),a=new L8(T8,a,a9()),a.connect(b,qSa()),a.subscribe("beforeDisconnect",function(c){F6("yt-remote-before-disconnect",c)}),a.subscribe("beforeDispose",function(){c9()&&(c9(),h9(null))}),a.subscribe("browserChannelAuthError",function(){var c=b9();
c&&"shortLived"==c.idType&&(s8()?p8().handleBrowserChannelAuthError():n8("refreshLoungeToken called before API ready."))}),h9(a))},lSa=function(){var a=$8();
a?(X8("Resume connection to: "+J6(a)),g9(a,0)):(S6(),QRa(),X8("Skipping connecting because no session screen found."))},jSa=function(){var a=a9();
if(g.Sb(a)){a=Q6();var b=g.mz("yt-remote-session-name")||"",c=g.mz("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},a9=function(){return g.Ha("yt.mdx.remote.channelParams_")||{}},l9=function(a,b,c){g.E.call(this);
var d=this;this.l=a;this.I=b;this.Pb=c;this.events=new g.kN(this);this.ea=this.events.N(this.I,"onVolumeChange",function(e){rSa(d,e)});
this.C=!1;this.suggestion=null;this.G=new g.sK(64);this.i=new g.J(this.TL,500,this);this.u=new g.J(this.UL,1E3,this);this.L=new Y6(this.gW,0,this);this.B={};this.V=new g.J(this.BM,1E3,this);this.J=new Z6(this.seekTo,1E3,this);this.X=g.Ia;g.F(this,this.events);this.events.N(b,"onCaptionsTrackListChanged",this.dT);this.events.N(b,"captionschanged",this.lS);this.events.N(b,"captionssettingschanged",this.aM);this.events.N(b,"videoplayerreset",this.Vy);this.events.N(b,"mdxautoplaycancel",function(){d.Pb.fI()});
a=this.Pb;a.isDisposed();a.subscribe("proxyStateChange",this.RK,this);a.subscribe("remotePlayerChange",this.Cv,this);a.subscribe("remoteQueueChange",this.Vy,this);a.subscribe("previousNextChange",this.OK,this);a.subscribe("nowAutoplaying",this.IK,this);a.subscribe("autoplayDismissed",this.lK,this);g.F(this,this.i);g.F(this,this.u);g.F(this,this.L);g.F(this,this.V);g.F(this,this.J);this.aM();this.Vy();this.Cv()},rSa=function(a,b){if(m9(a)){a.Pb.unsubscribe("remotePlayerChange",a.Cv,a);
var c=Math.round(b.volume);b=!!b.muted;var d=E8(a.Pb);if(c!==d.volume||b!==d.muted)a.Pb.setVolume(c,b),a.V.start();a.Pb.subscribe("remotePlayerChange",a.Cv,a)}},sSa=function(a){a.Rb(0);
a.i.stop();a.Kb(new g.sK(64))},n9=function(a,b){if(m9(a)&&!a.C){var c=null;
b&&(c={style:a.I.getSubtitlesUserSettings()},g.$b(c,b));a.Pb.sG(a.I.getVideoData(1).videoId,c);a.B=E8(a.Pb).trackData}},o9=function(a,b){var c=a.I.getPlaylist();
if(null===c||void 0===c?0:c.listId){var d=c.index;var e=c.listId.toString()}c=a.I.getVideoData(1);a.Pb.playVideo(c.videoId,b,d,e,c.playerParams,c.La,PPa(c));a.Kb(new g.sK(1))},tSa=function(a,b){if(b){var c=a.I.getOption("captions","tracklist",{fJ:1});
c&&c.length?(a.I.setOption("captions","track",b),a.C=!1):(a.I.loadModule("captions"),a.C=!0)}else a.I.setOption("captions","track",{})},m9=function(a){return E8(a.Pb).videoId===a.I.getVideoData(1).videoId},p9=function(){g.V.call(this,{D:"div",
K:"ytp-mdx-manual-pairing-popup-dialog",U:{role:"dialog"},S:[{D:"div",K:"ytp-mdx-manual-pairing-popup-dialog-inner-content",S:[{D:"div",K:"ytp-mdx-manual-pairing-popup-title",ra:"\u4f7f\u7528\u914d\u5bf9\u7801\u5728\u7f51\u9875\u4e0a\u5173\u8054\u60a8\u7684\u7535\u89c6\u7684\u529f\u80fd\u5373\u5c06\u505c\u7528"},{D:"div",K:"ytp-mdx-manual-pairing-popup-buttons",S:[{D:"button",Ea:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],ra:"\u4e86\u89e3\u8be6\u60c5"},{D:"button",Ea:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],
ra:"\u786e\u5b9a"}]}]}]});this.i=new g.YL(this,250);this.learnMoreButton=this.Ca("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.Ca("ytp-mdx-manual-pairing-popup-ok");g.F(this,this.i);this.N(this.learnMoreButton,"click",this.l);this.N(this.okButton,"click",this.u)},q9=function(){g.V.call(this,{D:"div",
K:"ytp-mdx-popup-dialog",U:{role:"dialog"},S:[{D:"div",K:"ytp-mdx-popup-dialog-inner-content",S:[{D:"div",K:"ytp-mdx-popup-title",ra:"\u60a8\u5df2\u9000\u51fa\u5e10\u53f7"},{D:"div",K:"ytp-mdx-popup-description",ra:"\u60a8\u89c2\u770b\u7684\u89c6\u9891\u53ef\u80fd\u4f1a\u6dfb\u52a0\u5230\u7535\u89c6\u7684\u89c2\u770b\u8bb0\u5f55\u4e2d\uff0c\u5e76\u5f71\u54cd\u7535\u89c6\u4e0a\u7684\u63a8\u8350\u5185\u5bb9\u3002\u4e3a\u907f\u514d\u53d1\u751f\u8fd9\u79cd\u60c5\u51b5\uff0c\u8bf7\u53d6\u6d88\u5e76\u5728\u8ba1\u7b97\u673a\u4e0a\u767b\u5f55 YouTube\u3002"},
{D:"div",K:"ytp-mdx-privacy-popup-buttons",S:[{D:"button",Ea:["ytp-button","ytp-mdx-privacy-popup-cancel"],ra:"\u53d6\u6d88"},{D:"button",Ea:["ytp-button","ytp-mdx-privacy-popup-confirm"],ra:"\u786e\u8ba4"}]}]}]});this.i=new g.YL(this,250);this.cancelButton=this.Ca("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.Ca("ytp-mdx-privacy-popup-confirm");g.F(this,this.i);this.N(this.cancelButton,"click",this.l);this.N(this.confirmButton,"click",this.u)},r9=function(a){g.V.call(this,{D:"div",
K:"ytp-remote",S:[{D:"div",K:"ytp-remote-display-status",S:[{D:"div",K:"ytp-remote-display-status-icon",S:[g.rra()]},{D:"div",K:"ytp-remote-display-status-text",ra:"{{statustext}}"}]}]});this.api=a;this.i=new g.YL(this,250);g.F(this,this.i);this.N(a,"presentingplayerstatechange",this.l);uSa(this,a.ub())},uSa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
b=g.U(b,128)?g.TI("\u5728$RECEIVER_NAME\u4e0a\u51fa\u73b0\u9519\u8bef",c):b.xc()||g.U(b,4)?g.TI("\u6b63\u5728$RECEIVER_NAME\u4e0a\u64ad\u653e",c):g.TI("\u5df2\u8fde\u63a5\u5230$RECEIVER_NAME",c);a.Sa("statustext",b);a.i.show()}else a.i.hide()},s9=function(a,b){g.jQ.call(this,"\u64ad\u653e\u8bbe\u5907",0,a,b);
this.I=a;this.Ln={};this.N(a,"onMdxReceiversChange",this.C);this.N(a,"presentingplayerstatechange",this.C);this.C()},t9=function(a){g.tN.call(this,a);
this.lj={key:L6(),name:"\u6b64\u8ba1\u7b97\u673a"};this.Uh=null;this.subscriptions=[];this.dE=this.Pb=null;this.Ln=[this.lj];this.Gm=this.lj;this.kd=new g.sK(64);this.EJ=0;this.jf=-1;this.Tr=null;this.Iv=this.wy=!1;this.Wl=this.hs=null;if(!g.KF(this.player.T())&&!g.LF(this.player.T())){a=this.player;var b=g.YM(a);b&&(b=b.Um())&&(b=new s9(a,b),g.F(this,b));b=new r9(a);g.F(this,b);g.hN(a,b.element,4);this.hs=new q9;g.F(this,this.hs);g.hN(a,this.hs.element,4);g.S(this.player.T().experiments,"pair_servlet_deprecation_warning_enabled")&&
!g.S(this.player.T().experiments,"deprecate_pair_servlet_enabled")&&(this.Tr=new p9,g.F(this,this.Tr),g.hN(a,this.Tr.element,4));this.Iv=!!$8();this.wy=!!g.mz("yt-remote-manual-pairing-warning-shown")}},u9=function(a){a.Wl&&(a.player.removeEventListener("presentingplayerstatechange",a.Wl),a.Wl=null)},vSa=function(a,b,c){a.kd=c;
a.player.Z("presentingplayerstatechange",new g.GI(c,b))},wSa=function(a,b,c){var d=!1;
1===b?d=!a.Iv:2===b&&(d=!a.wy);d&&g.II(c,8)&&(a.player.pauseVideo(),u9(a))},v9=function(a,b){if(b.key!==a.Gm.key)if(b.key===a.lj.key)f9();
else{if(a.Tr&&!a.wy&&b!==a.lj&&"cast-selector-receiver"!==b.key&&g.bG(a.player.T()))xSa(a);else{var c;(c=!g.S(a.player.T().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.N("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.N("SESSION_INDEX")&&!g.N("LOGGED_IN")))||a.Iv||!a.hs);(c?0:g.bG(a.player.T())||g.fG(a.player.T()))&&ySa(a)}a.Gm=b;if(!a.player.T().Y("disable_mdx_connection_in_mdx_module_for_music_web")||!g.LF(a.player.T())){var d=a.player.getPlaylistId();c=a.player.getVideoData(1);
var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&g.S(a.player.T().experiments,"should_clear_video_data_on_player_cued_unstarted"))a=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.length;l++)h[l]=f.ib(l).videoId}else h=[e];f=a.player.getCurrentTime(1);a={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.La,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=PPa(c))&&(a.locationInfo=c)}X8("Connecting to: "+
g.Qh(b));"cast-selector-receiver"==b.key?(Z8(a||null),b=a||null,s8()?p8().setLaunchParams(b):n8("setLaunchParams called before ready.")):!a&&i9()&&W8()==b.key?F6("yt-remote-connection-change",!0):(f9(),Z8(a||null),a=V8().Bh(),(b=N6(a,b.key))&&g9(b,1))}}},ySa=function(a){a.player.ub().xc()?a.player.pauseVideo():(a.Wl=function(b){wSa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.Wl));
a.hs&&a.hs.Xc();c9()||(k9=!0)},xSa=function(a){a.player.ub().xc()?a.player.pauseVideo():(a.Wl=function(b){wSa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.Wl));
a.Tr&&a.Tr.Xc();c9()||(k9=!0)},yQa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},l7={"'":"\\'"},VPa={fX:"atp",S6:"ska",I5:"que",U3:"mus",R6:"sus",d0:"dsp",c6:"seq",x3:"mic",c_:"dpa",tX:"cds",S3:"mlm"},T6,P6="",oQa=jQa("loadCastFramework")||jQa("loadCastApplicationFramework"),qQa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Sa(Y6,g.E);g.k=Y6.prototype;g.k.zO=function(a){this.B=arguments;this.i=!1;this.Hb?this.u=g.Ra()+this.Mf:this.Hb=g.nh(this.C,this.Mf)};
g.k.stop=function(){this.Hb&&(g.B.clearTimeout(this.Hb),this.Hb=null);this.u=null;this.i=!1;this.B=[]};
g.k.pause=function(){++this.l};
g.k.resume=function(){this.l&&(--this.l,!this.l&&this.i&&(this.i=!1,this.G.apply(null,this.B)))};
g.k.va=function(){this.stop();Y6.Vd.va.call(this)};
g.k.AO=function(){this.Hb&&(g.B.clearTimeout(this.Hb),this.Hb=null);this.u?(this.Hb=g.nh(this.C,this.u-g.Ra()),this.u=null):this.l?this.i=!0:(this.i=!1,this.G.apply(null,this.B))};g.v(Z6,g.E);g.k=Z6.prototype;g.k.nG=function(a){this.u=arguments;this.Hb||this.l?this.i=!0:$6(this)};
g.k.stop=function(){this.Hb&&(g.B.clearTimeout(this.Hb),this.Hb=null,this.i=!1,this.u=null)};
g.k.pause=function(){this.l++};
g.k.resume=function(){this.l--;this.l||!this.i||this.Hb||(this.i=!1,$6(this))};
g.k.va=function(){g.E.prototype.va.call(this);this.stop()};a7.prototype.stringify=function(a){return g.B.JSON.stringify(a,void 0)};
a7.prototype.parse=function(a){return g.B.JSON.parse(a,void 0)};var c7=new g.Lf;g.v(sQa,g.mf);g.k=e7.prototype;g.k.Co=null;g.k.Aj=!1;g.k.Ls=null;g.k.uF=null;g.k.rs=null;g.k.Es=null;g.k.zm=null;g.k.On=null;g.k.Up=null;g.k.Ve=null;g.k.zw=0;g.k.Ej=null;g.k.bA=null;g.k.tm=null;g.k.qt=-1;g.k.IL=!0;g.k.Po=!1;g.k.QA=0;g.k.mz=null;var wQa={},h7={};g.k=e7.prototype;g.k.setTimeout=function(a){this.C=a};
g.k.BO=function(a){a=a.target;var b=this.mz;b&&3==g.Pi(a)?b.nG():this.HM(a)};
g.k.HM=function(a){try{if(a==this.Ve)a:{var b=g.Pi(this.Ve),c=this.Ve.l,d=this.Ve.getStatus();if(g.ie&&!g.ce(10)||g.mg&&!g.be("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Wk&&!g.Ui(this.Ve))break a;this.Po||4!=b||7==c||(8==c||0>=d?this.i.nj(3):this.i.nj(2));m7(this);var e=this.Ve.getStatus();this.qt=e;var f=g.Ui(this.Ve);(this.Aj=200==e)?(4==b&&j7(this),this.G?(xQa(this,b,f),g.Wk&&this.Aj&&3==b&&(this.B.Qa(this.u,"tick",this.cV),this.u.start())):i7(this,f),this.Aj&&!this.Po&&(4==b?this.i.Lw(this):
(this.Aj=!1,g7(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.tm=3,d7(13)):(this.tm=0,d7(14)),j7(this),k7(this))}}catch(h){this.Ve&&g.Ui(this.Ve)}finally{}};
g.k.cV=function(){var a=g.Pi(this.Ve),b=g.Ui(this.Ve);this.zw<b.length&&(m7(this),xQa(this,a,b),this.Aj&&4!=a&&g7(this))};
g.k.MU=function(a){b7((0,g.C)(this.LU,this,a),0)};
g.k.LU=function(a){this.Po||(m7(this),i7(this,a),g7(this))};
g.k.ZK=function(a){b7((0,g.C)(this.KU,this,a),0)};
g.k.KU=function(a){this.Po||(j7(this),this.Aj=a,this.i.Lw(this),this.i.nj(4))};
g.k.cancel=function(){this.Po=!0;j7(this)};
g.k.TU=function(){this.Ls=null;var a=Date.now();0<=a-this.uF?(2!=this.Es&&this.i.nj(3),j7(this),this.tm=2,d7(18),k7(this)):AQa(this,this.uF-a)};
g.k.getLastError=function(){return this.tm};g.k=DQa.prototype;g.k.RA=null;g.k.gh=null;g.k.nz=!1;g.k.VL=null;g.k.nx=null;g.k.lD=null;g.k.SA=null;g.k.Pa=null;g.k.Sk=-1;g.k.ut=null;g.k.Gt=null;g.k.connect=function(a){this.SA=a;a=o7(this.i,null,this.SA);d7(3);this.VL=Date.now();var b=this.i.J;null!=b?(this.ut=b[0],(this.Gt=b[1])?(this.Pa=1,EQa(this)):(this.Pa=2,q7(this))):(C6(a,"MODE","init"),this.gh=new e7(this,void 0,void 0,void 0),this.gh.Co=this.RA,f7(this.gh,a,!1,null,!0),this.Pa=0)};
g.k.vP=function(a){if(a)this.Pa=2,q7(this);else{d7(4);var b=this.i;b.Tj=b.Em.Sk;x7(b,9)}a&&this.nj(2)};
g.k.XB=function(a){return this.i.XB(a)};
g.k.abort=function(){this.gh&&(this.gh.cancel(),this.gh=null);this.Sk=-1};
g.k.df=function(){return!1};
g.k.SK=function(a,b){this.Sk=a.qt;if(0==this.Pa)if(b){try{var c=this.l.parse(b)}catch(d){a=this.i;a.Tj=this.Sk;x7(a,2);return}this.ut=c[0];this.Gt=c[1]}else a=this.i,a.Tj=this.Sk,x7(a,2);else if(2==this.Pa)if(this.nz)d7(7),this.lD=Date.now();else if("11111"==b){if(d7(6),this.nz=!0,this.nx=Date.now(),a=this.nx-this.VL,!g.ie||g.ce(10)||500>a)this.Sk=200,this.gh.cancel(),d7(12),p7(this.i,this,!0)}else d7(8),this.nx=this.lD=Date.now(),this.nz=!1};
g.k.Lw=function(){this.Sk=this.gh.qt;if(this.gh.Aj)0==this.Pa?this.Gt?(this.Pa=1,EQa(this)):(this.Pa=2,q7(this)):2==this.Pa&&((!g.ie||g.ce(10)?!this.nz:200>this.lD-this.nx)?(d7(11),p7(this.i,this,!1)):(d7(12),p7(this.i,this,!0)));else{0==this.Pa?d7(9):2==this.Pa&&d7(10);var a=this.i;this.gh.getLastError();a.Tj=this.Sk;x7(a,2)}};
g.k.bw=function(){return this.i.bw()};
g.k.isActive=function(){return this.i.isActive()};
g.k.nj=function(a){this.i.nj(a)};g.k=r7.prototype;g.k.Sj=null;g.k.Yt=null;g.k.Ng=null;g.k.ze=null;g.k.TA=null;g.k.ox=null;g.k.yH=null;g.k.Mw=null;g.k.Zu=0;g.k.ER=0;g.k.Hf=null;g.k.Lm=null;g.k.ql=null;g.k.Yo=null;g.k.Em=null;g.k.Zz=null;g.k.Or=-1;g.k.DJ=-1;g.k.Tj=-1;g.k.xr=0;g.k.Vq=0;g.k.Qo=8;g.Sa(GQa,g.mf);g.Sa(HQa,g.mf);g.k=r7.prototype;g.k.connect=function(a,b,c,d,e){d7(0);this.TA=b;this.Yt=c||{};d&&void 0!==e&&(this.Yt.OSID=d,this.Yt.OAID=e);this.C?(b7((0,g.C)(this.SH,this,a),100),LQa(this)):this.SH(a)};
g.k.SH=function(a){this.Em=new DQa(this);this.Em.RA=this.Sj;this.Em.l=this.B;this.Em.connect(a)};
g.k.df=function(){return 0==this.Pa};
g.k.getState=function(){return this.Pa};
g.k.XK=function(a){this.Lm=null;PQa(this,a)};
g.k.WK=function(){this.ql=null;this.ze=new e7(this,this.l,"rpc",this.G);this.ze.Co=this.Sj;this.ze.QA=0;var a=this.yH.clone();g.rk(a,"RID","rpc");g.rk(a,"SID",this.l);g.rk(a,"CI",this.Zz?"0":"1");g.rk(a,"AID",this.Or);s7(this,a);if(!g.ie||g.ce(10))g.rk(a,"TYPE","xmlhttp"),f7(this.ze,a,!0,this.Mw,!1);else{g.rk(a,"TYPE","html");var b=this.ze,c=!!this.Mw;b.Es=3;b.zm=B6(a.clone());zQa(b,c)}};
g.k.SK=function(a,b){if(0!=this.Pa&&(this.ze==a||this.Ng==a))if(this.Tj=a.qt,this.Ng==a&&3==this.Pa)if(7<this.Qo){try{var c=this.B.parse(b)}catch(d){c=null}if(Array.isArray(c)&&3==c.length)if(a=c,0==a[0])a:{if(!this.ql){if(this.ze)if(this.ze.rs+3E3<this.Ng.rs)u7(this),this.ze.cancel(),this.ze=null;else break a;w7(this);d7(19)}}else this.DJ=a[1],0<this.DJ-this.Or&&37500>a[2]&&this.Zz&&0==this.Vq&&!this.Yo&&(this.Yo=b7((0,g.C)(this.iS,this),6E3));else x7(this,11)}else null!=b&&x7(this,11);else if(this.ze==
a&&u7(this),!g.vc(b))for(a=this.B.parse(b),b=0;b<a.length;b++)c=a[b],this.Or=c[0],c=c[1],2==this.Pa?"c"==c[0]?(this.l=c[1],this.Mw=c[2],c=c[3],null!=c?this.Qo=c:this.Qo=6,this.Pa=3,this.Hf&&this.Hf.OH(),this.yH=o7(this,this.bw()?this.Mw:null,this.TA),QQa(this)):"stop"==c[0]&&x7(this,7):3==this.Pa&&("stop"==c[0]?x7(this,7):"noop"!=c[0]&&this.Hf&&this.Hf.NH(c),this.Vq=0)};
g.k.iS=function(){null!=this.Yo&&(this.Yo=null,this.ze.cancel(),this.ze=null,w7(this),d7(20))};
g.k.Lw=function(a){if(this.ze==a){u7(this);this.ze=null;var b=2}else if(this.Ng==a)this.Ng=null,b=1;else return;this.Tj=a.qt;if(0!=this.Pa)if(a.Aj)if(1==b){b=Date.now()-a.rs;var c=c7;c.dispatchEvent(new GQa(c,a.Up?a.Up.length:0,b,this.xr));t7(this);this.u.length=0}else QQa(this);else{c=a.getLastError();var d;if(!(d=3==c||7==c||0==c&&0<this.Tj)){if(d=1==b)this.Ng||this.Lm||1==this.Pa||2<=this.xr?d=!1:(this.Lm=b7((0,g.C)(this.XK,this,a),RQa(this,this.xr)),this.xr++,d=!0);d=!(d||2==b&&w7(this))}if(d)switch(c){case 1:x7(this,
5);break;case 4:x7(this,10);break;case 3:x7(this,6);break;case 7:x7(this,12);break;default:x7(this,2)}}};
g.k.WP=function(a){if(!g.jb(arguments,this.Pa))throw Error("Unexpected channel state: "+this.Pa);};
g.k.OV=function(a){a?d7(2):(d7(1),SQa(this,8))};
g.k.XB=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.Di;a.L=!1;return a};
g.k.isActive=function(){return!!this.Hf&&this.Hf.isActive(this)};
g.k.nj=function(a){var b=c7;b.dispatchEvent(new HQa(b,a))};
g.k.bw=function(){return!(!g.ie||g.ce(10))};
g.k=TQa.prototype;g.k.OH=function(){};
g.k.NH=function(){};
g.k.MH=function(){};
g.k.KB=function(){};
g.k.wI=function(){return{}};
g.k.isActive=function(){return!0};g.k=UQa.prototype;g.k.isEmpty=function(){return 0===this.i.length&&0===this.l.length};
g.k.clear=function(){this.i=[];this.l=[]};
g.k.contains=function(a){return g.jb(this.i,a)||g.jb(this.l,a)};
g.k.remove=function(a){var b=this.i;var c=(0,g.RJa)(b,a);0<=c?(g.nb(b,c),b=!0):b=!1;return b||g.ob(this.l,a)};
g.k.Qg=function(){for(var a=[],b=this.i.length-1;0<=b;--b)a.push(this.i[b]);var c=this.l.length;for(b=0;b<c;++b)a.push(this.l[b]);return a};g.Sa(y7,g.E);g.k=y7.prototype;g.k.EU=function(){this.Mf=Math.min(3E5,2*this.Mf);this.u();this.l&&this.start()};
g.k.start=function(){var a=this.Mf+15E3*Math.random();g.Hq(this.i,a);this.l=Date.now()+a};
g.k.stop=function(){this.i.stop();this.l=0};
g.k.isActive=function(){return this.i.isActive()};
g.k.reset=function(){this.i.stop();this.Mf=5E3};g.Sa(z7,TQa);g.k=z7.prototype;g.k.subscribe=function(a,b,c){return this.u.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.u.unsubscribe(a,b,c)};
g.k.Rf=function(a){return this.u.Rf(a)};
g.k.Z=function(a,b){return this.u.Z.apply(this.u,arguments)};
g.k.dispose=function(){this.ea||(this.ea=!0,g.jf(this.u),XQa(this),g.jf(this.l),this.l=null,this.X=function(){return""})};
g.k.isDisposed=function(){return this.ea};
g.k.connect=function(a,b,c){if(!this.i||2!=this.i.getState()){this.V="";this.l.stop();this.C=a||null;this.B=b||0;a=this.xa+"/test";b=this.xa+"/bind";var d=new r7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.ya),e=this.i;e&&(e.Hf=null);d.Hf=this;this.i=d;A7(this);if(this.i){d=g.N("ID_TOKEN");var f=this.i.Sj||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.i.Sj=f}e?(3!=e.getState()&&0==NQa(e)||e.getState(),this.i.connect(a,b,this.G,e.l,e.Or)):c?this.i.connect(a,
b,this.G,c.sessionId,c.arrayId):this.i.connect(a,b,this.G)}};
g.k.sendMessage=function(a,b){a={_sc:a};b&&g.$b(a,b);this.l.isActive()||2==(this.i?this.i.getState():0)?this.J.push(a):B7(this)&&(A7(this),MQa(this.i,a))};
g.k.OH=function(){this.l.reset();this.C=null;this.B=0;if(this.J.length){var a=this.J;this.J=[];for(var b=0,c=a.length;b<c;++b)MQa(this.i,a[b])}this.Z("handlerOpened")};
g.k.MH=function(a){var b=2==a&&401==this.i.Tj;4==a||b||this.l.start();this.Z("handlerError",a,b)};
g.k.KB=function(a){if(!this.l.isActive())this.Z("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.J.push(d)}};
g.k.wI=function(){var a={v:2};this.V&&(a.gsessionid=this.V);0!=this.B&&(a.ui=""+this.B);0!=this.L&&(a.ui=""+this.L);this.C&&g.$b(a,this.C);return a};
g.k.NH=function(a){"S"==a[0]?this.V=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),KQa(this.i)):this.Z("handlerMessage",new VQa(a[0],a[1]))};
g.k.Bz=function(a){(this.G.loungeIdToken=a)||this.l.stop();if(this.Aa&&this.i){var b=this.i.Sj||{};a?b["X-YouTube-LoungeId-Token"]=a:delete b["X-YouTube-LoungeId-Token"];this.i.Sj=b}};
g.k.tV=function(){this.l.isActive();0==NQa(this.i)&&this.connect(this.C,this.B)};C7.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
C7.prototype.u=function(a,b){a(Error("Request error: "+b.status))};
C7.prototype.C=function(a){a(Error("request timed out"))};var dRa=Date.now(),F7=null,I7=Array(50),H7=-1,J7=!1;g.Sa(K7,g.P);K7.prototype.Bh=function(){return this.screens};
K7.prototype.contains=function(a){return!!M6(this.screens,a)};
K7.prototype.get=function(a){return a?N6(this.screens,a):null};
K7.prototype.info=function(a){G7(this.G,a)};g.v(L7,g.P);g.k=L7.prototype;g.k.start=function(){!this.i&&isNaN(this.Hb)&&this.gL()};
g.k.stop=function(){this.i&&(this.i.abort(),this.i=null);isNaN(this.Hb)||(g.Zs(this.Hb),this.Hb=NaN)};
g.k.va=function(){this.stop();g.P.prototype.va.call(this)};
g.k.gL=function(){this.Hb=NaN;this.i=g.dt(D7(this.u,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:this.J},timeout:5E3,onSuccess:(0,g.C)(this.DO,this),onError:(0,g.C)(this.CO,this),onTimeout:(0,g.C)(this.EO,this)})};
g.k.DO=function(a,b){this.i=null;a=b.screen||{};a.dialId=this.B;a.name=this.G;b=-1;this.C&&a.shortLivedLoungeToken&&a.shortLivedLoungeToken.value&&a.shortLivedLoungeToken.refreshIntervalMs&&(a.screenIdType="shortLived",a.loungeToken=a.shortLivedLoungeToken.value,b=a.shortLivedLoungeToken.refreshIntervalMs);this.Z("pairingComplete",new H6(a),b)};
g.k.CO=function(a){this.i=null;a.status&&404==a.status?this.l>=zSa.length?this.Z("pairingFailed",Error("DIAL polling timed out")):(a=zSa[this.l],this.Hb=g.Xs((0,g.C)(this.gL,this),a),this.l++):this.Z("pairingFailed",Error("Server error "+a.status))};
g.k.EO=function(){this.i=null;this.Z("pairingFailed",Error("Server not responding"))};
var zSa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Sa(N7,K7);g.k=N7.prototype;g.k.start=function(){M7(this)&&this.Z("screenChange");!g.mz("yt-remote-lounge-token-expiration")&&hRa(this);g.Zs(this.i);this.i=g.Xs((0,g.C)(this.start,this),1E4)};
g.k.add=function(a,b){M7(this);eRa(this,a);O7(this,!1);this.Z("screenChange");b(a);a.token||hRa(this)};
g.k.remove=function(a,b){var c=M7(this);gRa(this,a)&&(O7(this,!1),c=!0);b(a);c&&this.Z("screenChange")};
g.k.Xz=function(a,b,c,d){var e=M7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,O7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.Z("screenChange")};
g.k.va=function(){g.Zs(this.i);N7.Vd.va.call(this)};
g.k.vQ=function(a){M7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}O7(this,!b);b&&G7(this.G,"Missed "+b+" lounge tokens.")};
g.k.uQ=function(a){G7(this.G,"Requesting lounge tokens failed: "+a)};g.v(Q7,g.P);g.k=Q7.prototype;g.k.start=function(){var a=parseInt(g.mz("yt-remote-fast-check-period")||"0",10);(this.B=g.Ra()-144E5<a?0:a)?T7(this):(this.B=g.Ra()+3E5,g.lz("yt-remote-fast-check-period",this.B),this.qE())};
g.k.isEmpty=function(){return g.Sb(this.i)};
g.k.update=function(){P7("Updating availability on schedule.");var a=this.G(),b=g.Fb(this.i,function(c,d){return c&&!!N6(a,d)},this);
S7(this,b)};
g.k.va=function(){g.Zs(this.u);this.u=NaN;this.l&&(this.l.abort(),this.l=null);g.P.prototype.va.call(this)};
g.k.qE=function(){g.Zs(this.u);this.u=NaN;this.l&&this.l.abort();var a=jRa(this);if(D6(a)){var b=D7(this.C,"/pairing/get_screen_availability");this.l=E7(this.C,b,{lounge_token:g.Mb(a).join(",")},(0,g.C)(this.kU,this,a),(0,g.C)(this.jU,this))}else S7(this,{}),T7(this)};
g.k.kU=function(a,b){this.l=null;var c=g.Mb(jRa(this));if(g.Ab(c,g.Mb(a))){b=b.screens||[];c={};for(var d=0,e=b.length;d<e;++d)c[a[b[d].loungeToken]]="online"==b[d].status;S7(this,c);T7(this)}else this.Wd("Changing Screen set during request."),this.qE()};
g.k.jU=function(a){this.Wd("Screen availability failed: "+a);this.l=null;T7(this)};
g.k.Wd=function(a){G7("OnlineScreenService",a)};g.Sa(U7,K7);g.k=U7.prototype;g.k.start=function(){this.l.start();this.i.start();this.screens.length&&(this.Z("screenChange"),this.i.isEmpty()||this.Z("onlineScreenChange"))};
g.k.add=function(a,b,c){this.l.add(a,b,c)};
g.k.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.k.Xz=function(a,b,c,d){this.l.contains(a)?this.l.Xz(a,b,c,d):(a="Updating name of unknown screen: "+a.name,G7(this.G,a),d(Error(a)))};
g.k.Bh=function(a){return a?this.screens:g.qb(this.screens,g.To(this.u,function(b){return!this.contains(b)},this))};
g.k.oG=function(){return g.To(this.Bh(!0),function(a){return!!this.i.i[a.id]},this)};
g.k.pG=function(a,b,c,d,e,f){var h=this;this.info("getDialScreenByPairingCode "+a+" / "+b);var l=new L7(this.B,a,b,c,d);l.subscribe("pairingComplete",function(m,n){g.jf(l);e(V7(h,m),n)});
l.subscribe("pairingFailed",function(m){g.jf(l);f(m)});
l.start();return(0,g.C)(l.stop,l)};
g.k.FO=function(a,b,c,d){g.dt(D7(this.B,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:a},timeout:5E3,onSuccess:(0,g.C)(function(e,f){e=new H6(f.screen||{});if(!e.name||nRa(this,e.name)){a:{f=e.name;for(var h=2,l=b(f,h);nRa(this,l);){h++;if(20<h)break a;l=b(f,h)}f=l}e.name=f}c(V7(this,e))},this),
onError:(0,g.C)(function(e){d(Error("pairing request failed: "+e.status))},this),
onTimeout:(0,g.C)(function(){d(Error("pairing request timed out."))},this)})};
g.k.va=function(){g.jf(this.l);g.jf(this.i);U7.Vd.va.call(this)};
g.k.EQ=function(){pRa(this);this.Z("screenChange");this.i.update()};
U7.prototype.dispose=U7.prototype.dispose;g.Sa(X7,g.P);g.k=X7.prototype;g.k.getScreen=function(){return this.B};
g.k.fg=function(a){this.isDisposed()||(a&&(Z7(this,""+a),this.Z("sessionFailed")),this.B=null,this.Z("sessionScreen",null))};
g.k.info=function(a){G7(this.Aa,a)};
g.k.qG=function(){return null};
g.k.DE=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.C)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.C)(function(){Z7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.va=function(){this.DE("");X7.Vd.va.call(this)};g.v($7,X7);g.k=$7.prototype;g.k.CE=function(a){if(this.l){if(this.l==a)return;Z7(this,"Overriding cast session with new session object");yRa(this);this.xa=!1;this.V="unknown";this.l.removeUpdateListener(this.X);this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.ya)}this.l=a;this.l.addUpdateListener(this.X);this.l.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.ya);uRa(this,"getMdxSessionStatus")};
g.k.Pr=function(a){this.info("launchWithParams no-op for Cast: "+g.Qh(a))};
g.k.stop=function(){this.l?this.l.stop((0,g.C)(function(){this.fg()},this),(0,g.C)(function(){this.fg(Error("Failed to stop receiver app."))},this)):this.fg(Error("Stopping cast device without session."))};
g.k.DE=function(){};
g.k.va=function(){this.info("disposeInternal");yRa(this);this.l&&(this.l.removeUpdateListener(this.X),this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.ya));this.l=null;X7.prototype.va.call(this)};
g.k.WU=function(a,b){if(!this.isDisposed())if(b)if(b=E6(b),g.Ma(b))switch(a=""+b.type,b=b.data||{},this.info("onYoutubeMessage_: "+a+" "+g.Qh(b)),a){case "mdxSessionStatus":sRa(this,b);break;case "loungeToken":vRa(this,b);break;default:Z7(this,"Unknown youtube message: "+a)}else Z7(this,"Unable to parse message.");else Z7(this,"No data in message.")};
g.k.LI=function(a,b,c,d){g.Zs(this.L);this.L=0;mRa(this.u,this.i.label,a,this.i.friendlyName,(0,g.C)(function(e){e?b(e):0<=d?(Z7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),this.L=g.Xs((0,g.C)(this.LI,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.qG=function(){return this.l};
g.k.GO=function(a){this.isDisposed()||a||(Z7(this,"Cast session died."),this.fg())};g.v(c8,X7);g.k=c8.prototype;g.k.CE=function(a){this.l=a;this.l.addUpdateListener(this.Da)};
g.k.Pr=function(a){this.Ja=a;this.ea()};
g.k.stop=function(){FRa(this);this.l?this.l.stop((0,g.C)(this.fg,this,null),(0,g.C)(this.fg,this,"Failed to stop DIAL device.")):this.fg()};
g.k.va=function(){FRa(this);this.l&&this.l.removeUpdateListener(this.Da);this.l=null;X7.prototype.va.call(this)};
g.k.HO=function(a){this.isDisposed()||a||(Z7(this,"DIAL session died."),this.C(),this.C=g.Ia,this.fg())};g.v(g8,X7);g8.prototype.stop=function(){this.fg()};
g8.prototype.CE=function(){};
g8.prototype.Pr=function(){g.Zs(this.l);this.l=NaN;var a=N6(this.u.Bh(),this.i.label);a?Y7(this,a):this.fg(Error("No such screen"))};
g8.prototype.va=function(){g.Zs(this.l);this.l=NaN;X7.prototype.va.call(this)};g.v(h8,g.P);g.k=h8.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.J);this.L||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED;a=a||this.V?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;var e=(0,g.C)(this.ST,this);c=new chrome.cast.ApiConfig(c,(0,g.C)(this.TK,this),e,d,a);c.customDialLaunchCallback=(0,g.C)(this.ES,this);chrome.cast.initialize(c,(0,g.C)(function(){this.isDisposed()||
(chrome.cast.addReceiverActionListener(this.C),aRa(),this.l.subscribe("onlineScreenChange",(0,g.C)(this.rG,this)),this.u=IRa(this),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.C)(function(f){this.Wd("Failed to set initial custom receivers: "+g.Qh(f))},this)),this.Z("yt-remote-cast2-availability-change",j8(this)),b(!0))},this),(0,g.C)(function(f){this.Wd("Failed to initialize API: "+g.Qh(f));
b(!1)},this))};
g.k.yV=function(a,b){i8("Setting connected screen ID: "+a+" -> "+b);if(this.i){var c=this.i.getScreen();if(!a||c&&c.id!=a)i8("Unsetting old screen status: "+this.i.i.friendlyName),k8(this,null)}if(a&&b){if(!this.i){c=N6(this.l.Bh(),a);if(!c){i8("setConnectedScreenStatus: Unknown screen.");return}if("shortLived"==c.idType){i8("setConnectedScreenStatus: Screen with id type to be short lived.");return}a=GRa(this,c);a||(i8("setConnectedScreenStatus: Connected receiver not custom..."),a=new chrome.cast.Receiver(c.uuid?
c.uuid:c.id,c.name),a.receiverType=chrome.cast.ReceiverType.CUSTOM,this.u.push(a),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.C)(function(d){this.Wd("Failed to set initial custom receivers: "+g.Qh(d))},this)));
i8("setConnectedScreenStatus: new active receiver: "+a.friendlyName);k8(this,new g8(this.l,a),!0)}this.i.DE(b)}else i8("setConnectedScreenStatus: no screen.")};
g.k.zV=function(a){this.isDisposed()?this.Wd("Setting connection data on disposed cast v2"):this.i?this.i.Pr(a):this.Wd("Setting connection data without a session")};
g.k.JO=function(){this.isDisposed()?this.Wd("Stopping session on disposed cast v2"):this.i?(this.i.stop(),k8(this,null)):i8("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.C)(this.TK,this),(0,g.C)(this.nU,this))};
g.k.va=function(){this.l.unsubscribe("onlineScreenChange",(0,g.C)(this.rG,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.C);var a=YQa,b=g.Ha("yt.mdx.remote.debug.handlers_");g.ob(b||[],a);g.jf(this.i);g.P.prototype.va.call(this)};
g.k.Wd=function(a){G7("Controller",a)};
g.k.VK=function(a,b){this.i==a&&(b||k8(this,null),this.Z("yt-remote-cast2-session-change",b))};
g.k.PT=function(a,b){if(!this.isDisposed())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),i8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.i)if(this.i.i.label!=a.label)i8("onReceiverAction_: Stopping active receiver: "+this.i.i.friendlyName),this.i.stop();else{i8("onReceiverAction_: Casting to active receiver.");this.i.getScreen()&&this.Z("yt-remote-cast2-session-change",this.i.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:k8(this,
new g8(this.l,a));break;case chrome.cast.ReceiverType.DIAL:k8(this,new c8(this.l,a,this.B,this.config_));break;case chrome.cast.ReceiverType.CAST:k8(this,new $7(this.l,a,this.config_));break;default:this.Wd("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.i&&this.i.i.label==a.label?this.i.stop():this.Wd("Stopping receiver w/o session: "+a.friendlyName)}else this.Wd("onReceiverAction_ called without receiver.")};
g.k.ES=function(a){if(this.isDisposed())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Wd("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.i?this.i.i:null;if(!c||c.label!=b.label)return this.Wd("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.i.getScreen())return i8("Reselecting dial screen."),
this.Z("yt-remote-cast2-session-change",this.i.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Wd('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);k8(this,new c8(this.l,b,this.B,this.config_))}b=this.i;b.L=a;b.L.appState==chrome.cast.DialAppState.RUNNING?(a=b.L.extraData||{},c=a.screenId||null,d8(b)&&a.loungeToken?a.loungeTokenRefreshIntervalMs?a=CRa(b,{name:b.i.friendlyName,screenId:a.screenId,loungeToken:a.loungeToken,dialId:b.L.receiver.label,
screenIdType:"shortLived"},a.loungeTokenRefreshIntervalMs):(g.fs(Error("No loungeTokenRefreshIntervalMs presents in additionalData: "+JSON.stringify(a)+".")),a=DRa(b,c)):a=DRa(b,c)):a=f8(b);return a};
g.k.TK=function(a){var b=this;if(!this.isDisposed()){i8("New cast session ID: "+a.sessionId);var c=a.receiver;if(c.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.i)if(c.receiverType==chrome.cast.ReceiverType.CAST)i8("Got resumed cast session before resumed mdx connection."),c.friendlyName=chrome.cast.unescape(c.friendlyName),k8(this,new $7(this.l,c,this.config_),!0);else{this.Wd("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var d=this.i.i,e=N6(this.l.Bh(),
d.label);e&&I6(e,c.label)&&d.receiverType!=chrome.cast.ReceiverType.CAST&&c.receiverType==chrome.cast.ReceiverType.CAST&&(i8("onSessionEstablished_: manual to cast session change "+c.friendlyName),g.jf(this.i),this.i=new $7(this.l,c,this.config_),this.i.subscribe("sessionScreen",(0,g.C)(this.VK,this,this.i)),this.i.subscribe("sessionFailed",function(){return HRa(b,b.i)}),this.i.Pr(null));
this.i.CE(a)}}};
g.k.IO=function(){return this.i?this.i.qG():null};
g.k.nU=function(a){this.isDisposed()||(this.Wd("Failed to estabilish a session: "+g.Qh(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&k8(this,null),this.Z("yt-remote-cast2-session-failed"))};
g.k.ST=function(a){i8("Receiver availability updated: "+a);if(!this.isDisposed()){var b=j8(this);this.G=a==chrome.cast.ReceiverAvailability.AVAILABLE;j8(this)!=b&&this.Z("yt-remote-cast2-availability-change",j8(this))}};
g.k.rG=function(){this.isDisposed()||(this.u=IRa(this),i8("Updating custom receivers: "+g.Qh(this.u)),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.C)(function(){this.Wd("Failed to set custom receivers.")},this)),this.Z("yt-remote-cast2-availability-change",j8(this)))};
h8.prototype.setLaunchParams=h8.prototype.zV;h8.prototype.setConnectedScreenStatus=h8.prototype.yV;h8.prototype.stopSession=h8.prototype.JO;h8.prototype.getCastSession=h8.prototype.IO;h8.prototype.requestSession=h8.prototype.requestSession;h8.prototype.init=h8.prototype.init;h8.prototype.dispose=h8.prototype.dispose;var q8=[];g.k=v8.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";w8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.trackData=a.trackData,this.nk=a.hasPrevious,this.hasNext=a.hasNext,this.J=a.playerTime,this.G=a.playerTimeAt,this.B=a.seekableStart,this.i=a.seekableEnd,this.C=a.duration,this.L=a.loadedTime,this.u=a.liveIngestionTime,this.l=
!isNaN(this.u))};
g.k.xc=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.yj=function(a){this.C=isNaN(a)?0:a};
g.k.getDuration=function(){return this.l?this.C+x8(this):this.C};
g.k.clone=function(){return new v8(B8(this))};g.v(D8,g.P);g.k=D8.prototype;g.k.getState=function(){return this.Pa};
g.k.play=function(){F8(this)?(this.i?this.i.play(null,g.Ia,K8(this,"play")):J8(this,"play"),I8(this,1,z8(E8(this))),this.Z("remotePlayerChange")):G8(this,this.play)};
g.k.pause=function(){F8(this)?(this.i?this.i.pause(null,g.Ia,K8(this,"pause")):J8(this,"pause"),I8(this,2,z8(E8(this))),this.Z("remotePlayerChange")):G8(this,this.pause)};
g.k.seekTo=function(a){if(F8(this)){if(this.i){var b=E8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.xc()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ia,K8(this,"seekTo",{newTime:a}))}else J8(this,"seekTo",{newTime:a});I8(this,3,a);this.Z("remotePlayerChange")}else G8(this,g.Pa(this.seekTo,a))};
g.k.stop=function(){if(F8(this)){this.i?this.i.stop(null,g.Ia,K8(this,"stopVideo")):J8(this,"stopVideo");var a=E8(this);a.index=-1;a.videoId="";w8(a);H8(this,a);this.Z("remotePlayerChange")}else G8(this,this.stop)};
g.k.setVolume=function(a,b){if(F8(this)){var c=E8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.C)(function(){G7("CP","set receiver volume: "+d)},this),(0,g.C)(function(){this.Wd("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.C)(function(){G7("CP","set receiver muted: "+b)},this),(0,g.C)(function(){this.Wd("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);J8(this,"setVolume",e)}c.muted=b;c.volume=a;H8(this,c)}else G8(this,g.Pa(this.setVolume,a,b))};
g.k.sG=function(a,b){if(F8(this)){var c=E8(this);a={videoId:a};b&&(c.trackData={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},a.style=g.Qh(b.style),g.$b(a,c.trackData));J8(this,"setSubtitlesTrack",a);H8(this,c)}else G8(this,g.Pa(this.sG,a,b))};
g.k.setAudioTrack=function(a,b){F8(this)?(b=b.getLanguageInfo().getId(),J8(this,"setAudioTrack",{videoId:a,audioTrackId:b}),a=E8(this),a.audioTrackId=b,H8(this,a)):G8(this,g.Pa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){d=void 0===d?null:d;e=void 0===e?null:e;f=void 0===f?null:f;h=void 0===h?null:h;var l=E8(this),m={videoId:a};void 0!==c&&(m.currentIndex=c);A8(l,a,c||0);void 0!==b&&(y8(l,b),m.currentTime=b);d&&(m.listId=d);e&&(m.playerParams=e);f&&(m.clickTrackingParams=f);h&&(m.locationInfo=g.Qh(h));J8(this,"setPlaylist",m);d||H8(this,l)};
g.k.fz=function(a,b){if(F8(this)){if(a&&b){var c=E8(this);A8(c,a,b);H8(this,c)}J8(this,"previous")}else G8(this,g.Pa(this.fz,a,b))};
g.k.nextVideo=function(a,b){if(F8(this)){if(a&&b){var c=E8(this);A8(c,a,b);H8(this,c)}J8(this,"next")}else G8(this,g.Pa(this.nextVideo,a,b))};
g.k.fI=function(){F8(this)?J8(this,"dismissAutoplay"):G8(this,this.fI)};
g.k.dispose=function(){if(3!=this.Pa){var a=this.Pa;this.Pa=3;this.Z("proxyStateChange",a,this.Pa)}g.P.prototype.dispose.call(this)};
g.k.va=function(){URa(this);this.u=null;this.B.clear();C8(this,null);g.P.prototype.va.call(this)};
g.k.FE=function(a){if((a!=this.Pa||2==a)&&3!=this.Pa&&0!=a){var b=this.Pa;this.Pa=a;this.Z("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,0===b.i.length&&(b.i=b.l,b.i.reverse(),b.l=[]),a.i.pop().apply(this);else 3==a&&this.dispose()}};
g.k.LT=function(a,b){this.Z(a,b)};
g.k.oS=function(a){if(!a)this.vv(null),C8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=E8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)G7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,H8(this,b)}};
g.k.vv=function(a){G7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.J);if(this.i=a)this.i.addUpdateListener(this.J),VRa(this),this.Z("remotePlayerChange")};
g.k.nS=function(a){a?(VRa(this),this.Z("remotePlayerChange")):this.vv(null)};
g.k.YE=function(){J8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.wS=function(){var a=RRa();a&&C8(this,a)};
g.k.Wd=function(a){G7("CP",a)};g.v(L8,g.P);g.k=L8.prototype;
g.k.connect=function(a,b,c){c=void 0===c?!1:c;if(b){var d=b.listId,e=b.videoId,f=b.videoIds,h=b.playerParams,l=b.clickTrackingParams,m=b.index,n={videoId:e},p=b.currentTime,r=b.locationInfo;b=b.loopMode;void 0!==p&&(n.currentTime=5>=p?0:p);h&&(n.playerParams=h);r&&(n.locationInfo=r);l&&(n.clickTrackingParams=l);d&&(n.listId=d);f&&0<f.length&&(n.videoIds=f.join(","));void 0!==m&&(n.currentIndex=m);c&&(n.loopMode=b||"LOOP_MODE_OFF");d&&(this.hc.listId=d);this.hc.videoId=e;this.hc.index=m||0;this.hc.state=
3;y8(this.hc,p);this.B="UNSUPPORTED";c=c?"setInitialState":"setPlaylist";M8("Connecting with "+c+" and params: "+g.Qh(n));this.i.connect({method:c,params:g.Qh(n)},a,cQa())}else M8("Connecting without params"),this.i.connect({},a,cQa());YRa(this)};
g.k.Bz=function(a){this.i.Bz(a)};
g.k.dispose=function(){this.isDisposed()||(g.Ga("yt.mdx.remote.remoteClient_",null,void 0),this.Z("beforeDispose"),N8(this,3));g.P.prototype.dispose.call(this)};
g.k.va=function(){O8(this);Q8(this);P8(this);g.Zs(this.J);this.J=NaN;g.Zs(this.L);this.L=NaN;this.u=null;g.du(this.V);this.V.length=0;this.i.dispose();g.P.prototype.va.call(this);this.B=this.G=this.l=this.hc=this.i=null};
g.k.qQ=function(){this.qr(2)};
g.k.tS=function(){M8("Channel opened");this.xa&&(this.xa=!1,P8(this),this.X=g.Xs((0,g.C)(function(){M8("Timing out waiting for a screen.");this.qr(1)},this),15E3));
gQa(WQa(this.i),this.Da)};
g.k.pS=function(){M8("Channel closed");isNaN(this.C)?S6(!0):S6();this.dispose()};
g.k.qS=function(a,b){S6();isNaN(this.Bu())?(b&&"shortLived"==this.ya&&this.Z("browserChannelAuthError",a),M8("Channel error: "+a+" without reconnection"),this.dispose()):(this.xa=!0,M8("Channel error: "+a+" with reconnection in "+this.Bu()+" ms"),N8(this,2))};
g.k.pJ=function(a){if(!this.l||0===this.l.length)return!1;for(var b=g.q(this.l),c=b.next();!c.done;c=b.next())if(!c.value.capabilities.has(a))return!1;return!0};
g.k.sS=function(a){a.params?M8("Received: action="+a.action+", params="+g.Qh(a.params)):M8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=E6(a.params.devices);this.l=g.Se(a,function(c){return new G6(c)});
a=!!g.fb(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
aSa(this,a);a=this.pJ("mlm");this.Z("multiStateLoopEnabled",a);break;case "loungeScreenDisconnected":g.pb(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
aSa(this,!1);break;case "remoteConnected":var b=new G6(E6(a.params.device));g.fb(this.l,function(c){return b?c.id==b.id:!1})||QPa(this.l,b);
break;case "remoteDisconnected":b=new G6(E6(a.params.device));g.pb(this.l,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":cSa(this,a);break;case "nowPlaying":eSa(this,a);break;case "onStateChange":dSa(this,a);break;case "onAdStateChange":fSa(this,a);break;case "onVolumeChanged":gSa(this,a);break;case "onSubtitlesTrackChanged":bSa(this,a);break;case "nowAutoplaying":hSa(this,a);break;case "autoplayDismissed":this.Z("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.Z("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.Z("autoplayModeChange",this.B);"DISABLED"==this.B&&this.Z("autoplayDismissed");break;case "onHasPreviousNextChanged":iSa(this,a);break;case "requestAssistedSignIn":this.Z("assistedSignInRequested",a.params.authCode);break;case "onLoopModeChanged":this.Z("loopModeChange",a.params.loopMode);break;default:M8("Unrecognized action: "+a.action)}};
g.k.oV=function(){if(this.u){var a=this.u;this.u=null;this.hc.videoId!=a&&R8(this,"getNowPlaying")}};
g.k.lQ=function(){var a=3;this.isDisposed()||(a=0,isNaN(this.Bu())?B7(this.i)&&isNaN(this.C)&&(a=1):a=2);return a};
g.k.qr=function(a){M8("Disconnecting with "+a);g.Ga("yt.mdx.remote.remoteClient_",null,void 0);O8(this);this.Z("beforeDisconnect",a);1==a&&S6();XQa(this.i,a);this.dispose()};
g.k.jQ=function(){var a=this.hc;this.u&&(a=this.hc.clone(),A8(a,this.u,a.index));return B8(a)};
g.k.AV=function(a){var b=new v8(a);b.videoId&&b.videoId!=this.hc.videoId&&(this.u=b.videoId,g.Zs(this.J),this.J=g.Xs((0,g.C)(this.oV,this),5E3));var c=[];this.hc.listId==b.listId&&this.hc.videoId==b.videoId&&this.hc.index==b.index||c.push("remoteQueueChange");this.hc.playerState==b.playerState&&this.hc.volume==b.volume&&this.hc.muted==b.muted&&z8(this.hc)==z8(b)&&g.Qh(this.hc.trackData)==g.Qh(b.trackData)||c.push("remotePlayerChange");this.hc.reset(a);g.Cb(c,function(d){this.Z(d)},this)};
g.k.KI=function(){var a=this.i.G.id,b=g.fb(this.l,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Bu=function(){var a=this.i;return a.l.isActive()?a.l.l-Date.now():NaN};
g.k.gQ=function(){return this.B||"UNSUPPORTED"};
g.k.hQ=function(){return this.G||""};
g.k.KO=function(){if(!isNaN(this.Bu())){var a=this.i.l;g.Iq(a.i);a.start()}};
g.k.xV=function(a,b){R8(this,a,b);$Ra(this)};
g.k.tG=function(){var a=g.pt("SID","")||"",b=g.pt("SAPISID","")||"",c=g.pt("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.fe(g.Ya(a),2);b=g.fe(g.Ya(b),2);c=g.fe(g.Ya(c),2);return g.fe(g.Ya(a+","+b+","+c),2)};
L8.prototype.subscribe=L8.prototype.subscribe;L8.prototype.unsubscribeByKey=L8.prototype.Rf;L8.prototype.getProxyState=L8.prototype.lQ;L8.prototype.disconnect=L8.prototype.qr;L8.prototype.getPlayerContextData=L8.prototype.jQ;L8.prototype.setPlayerContextData=L8.prototype.AV;L8.prototype.getOtherConnectedRemoteId=L8.prototype.KI;L8.prototype.getReconnectTimeout=L8.prototype.Bu;L8.prototype.getAutoplayMode=L8.prototype.gQ;L8.prototype.getAutoplayVideoId=L8.prototype.hQ;L8.prototype.reconnect=L8.prototype.KO;
L8.prototype.sendMessage=L8.prototype.xV;L8.prototype.getXsrfToken=L8.prototype.tG;L8.prototype.isCapabilitySupportedOnConnectedDevices=L8.prototype.pJ;g.v(S8,K7);g.k=S8.prototype;g.k.Bh=function(a){return this.He.$_gs(a)};
g.k.contains=function(a){return!!this.He.$_c(a)};
g.k.get=function(a){return this.He.$_g(a)};
g.k.start=function(){this.He.$_st()};
g.k.add=function(a,b,c){this.He.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.He.$_r(a,b,c)};
g.k.Xz=function(a,b,c,d){this.He.$_un(a,b,c,d)};
g.k.va=function(){for(var a=0,b=this.i.length;a<b;++a)this.He.$_ubk(this.i[a]);this.i.length=0;this.He=null;K7.prototype.va.call(this)};
g.k.LO=function(){this.Z("screenChange")};
g.k.tT=function(){this.Z("onlineScreenChange")};
U7.prototype.$_st=U7.prototype.start;U7.prototype.$_gspc=U7.prototype.FO;U7.prototype.$_gsppc=U7.prototype.pG;U7.prototype.$_c=U7.prototype.contains;U7.prototype.$_g=U7.prototype.get;U7.prototype.$_a=U7.prototype.add;U7.prototype.$_un=U7.prototype.Xz;U7.prototype.$_r=U7.prototype.remove;U7.prototype.$_gs=U7.prototype.Bh;U7.prototype.$_gos=U7.prototype.oG;U7.prototype.$_s=U7.prototype.subscribe;U7.prototype.$_ubk=U7.prototype.Rf;var e9=null,k9=!1,T8=null,U8=null,j9=null,Y8=[];g.v(l9,g.E);g.k=l9.prototype;g.k.va=function(){g.E.prototype.va.call(this);this.i.stop();this.u.stop();this.L.stop();this.X();var a=this.Pb;a.unsubscribe("proxyStateChange",this.RK,this);a.unsubscribe("remotePlayerChange",this.Cv,this);a.unsubscribe("remoteQueueChange",this.Vy,this);a.unsubscribe("previousNextChange",this.OK,this);a.unsubscribe("nowAutoplaying",this.IK,this);a.unsubscribe("autoplayDismissed",this.lK,this);this.Pb=this.l=null};
g.k.ej=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.Pb.Pa)if(m9(this)){if(!E8(this.Pb).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":E8(this.Pb).xc()?this.Pb.pause():this.Pb.play();break;case "control_play":this.Pb.play();break;case "control_pause":this.Pb.pause();break;case "control_seek":this.J.nG(c[0],c[1]);break;case "control_subtitles_set_track":n9(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.I.getCurrentTime();o9(this,0===c?void 0:c);break;case "control_seek":o9(this,c[0]);break;case "control_subtitles_set_track":n9(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.lS=function(a){this.L.zO(a)};
g.k.gW=function(a){this.ej("control_subtitles_set_track",g.Sb(a)?null:a)};
g.k.aM=function(){var a=this.I.getOption("captions","track");g.Sb(a)||n9(this,a)};
g.k.Rb=function(a){this.l.Rb(a,this.I.getVideoData().lengthSeconds)};
g.k.dT=function(){g.Sb(this.B)||tSa(this,this.B);this.C=!1};
g.k.RK=function(a,b){this.u.stop();2===b&&this.UL()};
g.k.Cv=function(){if(m9(this)){this.i.stop();var a=E8(this.Pb);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.l.jf=1;break;case 1082:case 1083:this.l.jf=0;break;default:this.l.jf=-1}switch(a.playerState){case 1081:case 1:this.Kb(new g.sK(8));this.TL();break;case 1085:case 3:this.Kb(new g.sK(9));break;case 1083:case 0:this.Kb(new g.sK(2));this.J.stop();this.Rb(this.I.getVideoData().lengthSeconds);break;case 1084:this.Kb(new g.sK(4));break;case 2:this.Kb(new g.sK(4));this.Rb(z8(a));
break;case -1:this.Kb(new g.sK(64));break;case -1E3:this.Kb(new g.sK(128,{errorCode:"mdx.remoteerror",errorMessage:"\u6b64\u89c6\u9891\u65e0\u6cd5\u8fdc\u7a0b\u64ad\u653e\u3002"}))}a=E8(this.Pb).trackData;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,tSa(this,a));a=E8(this.Pb);-1===a.volume||Math.round(this.I.getVolume())===a.volume&&this.I.isMuted()===a.muted||this.V.isActive()||this.BM()}else sSa(this)};
g.k.OK=function(){this.I.Z("mdxpreviousnextchange")};
g.k.Vy=function(){m9(this)||sSa(this)};
g.k.IK=function(a){isNaN(a)||this.I.Z("mdxnowautoplaying",a)};
g.k.lK=function(){this.I.Z("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){m9(this)&&this.Pb.setAudioTrack(this.I.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===E8(this.Pb).playerState?o9(this,a):b&&this.Pb.seekTo(a)};
g.k.BM=function(){var a=this;if(m9(this)){var b=E8(this.Pb);this.events.jc(this.ea);b.muted?this.I.mute():this.I.unMute();this.I.setVolume(b.volume);this.ea=this.events.N(this.I,"onVolumeChange",function(c){rSa(a,c)})}};
g.k.TL=function(){this.i.stop();if(!this.Pb.isDisposed()){var a=E8(this.Pb);a.xc()&&this.Kb(new g.sK(8));this.Rb(z8(a));this.i.start()}};
g.k.UL=function(){this.u.stop();this.i.stop();var a=this.Pb.u.getReconnectTimeout();2==this.Pb.Pa&&!isNaN(a)&&this.u.start()};
g.k.Kb=function(a){this.u.stop();var b=this.G;if(!g.xK(b,a)){var c=g.U(a,2);c!==g.U(this.G,2)&&this.I.bq(c);this.G=a;vSa(this.l,b,a)}};g.v(p9,g.V);p9.prototype.Xc=function(){this.i.show()};
p9.prototype.Bb=function(){this.i.hide()};
p9.prototype.l=function(){g.$J("https://support.google.com/youtube/answer/7640706")};
p9.prototype.u=function(){F6("mdx-manual-pairing-popup-ok");this.Bb()};g.v(q9,g.V);q9.prototype.Xc=function(){this.i.show()};
q9.prototype.Bb=function(){this.i.hide()};
q9.prototype.l=function(){F6("mdx-privacy-popup-cancel");this.Bb()};
q9.prototype.u=function(){F6("mdx-privacy-popup-confirm");this.Bb()};g.v(r9,g.V);r9.prototype.l=function(a){uSa(this,a.state)};g.v(s9,g.jQ);s9.prototype.C=function(){var a=this.I.getOption("remote","receivers");a&&1<a.length&&!this.I.getOption("remote","quickCast")?(this.Ln=g.Db(a,this.i,this),g.kQ(this,g.Se(a,this.i)),a=this.I.getOption("remote","currentReceiver"),a=this.i(a),this.options[a]&&this.Rh(a),this.enable(!0)):this.enable(!1)};
s9.prototype.i=function(a){return a.key};
s9.prototype.Vi=function(a){return"cast-selector-receiver"===a?"\u6295\u5c04\u2026":this.Ln[a].name};
s9.prototype.uf=function(a){g.jQ.prototype.uf.call(this,a);this.I.setOption("remote","currentReceiver",this.Ln[a]);this.yb.Bb()};g.v(t9,g.tN);g.k=t9.prototype;
g.k.create=function(){var a=this.player.T(),b=g.IF(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:g.S(a.experiments,"mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:g.S(a.experiments,"enable_dial_short_lived_lounge_token"),enableCastLoungeToken:g.S(a.experiments,"enable_cast_short_lived_lounge_token")};mSa(b,a);this.subscriptions.push(g.Lu("yt-remote-before-disconnect",this.kS,this));this.subscriptions.push(g.Lu("yt-remote-connection-change",this.TT,this));this.subscriptions.push(g.Lu("yt-remote-receiver-availability-change",
this.QK,this));this.subscriptions.push(g.Lu("yt-remote-auto-connect",this.RT,this));this.subscriptions.push(g.Lu("yt-remote-receiver-resumed",this.QT,this));this.subscriptions.push(g.Lu("mdx-privacy-popup-confirm",this.fV,this));this.subscriptions.push(g.Lu("mdx-privacy-popup-cancel",this.eV,this));this.subscriptions.push(g.Lu("mdx-manual-pairing-popup-ok",this.pR,this));this.QK()};
g.k.load=function(){this.player.cancelPlayback();g.tN.prototype.load.call(this);this.Uh=new l9(this,this.player,this.Pb);var a=(a=qSa())?a.currentTime:0;var b=i9()?new D8(c9(),void 0):null;0==a&&b&&(a=z8(E8(b)));0!==a&&this.Rb(a);vSa(this,this.kd,this.kd);this.player.Jk(6)};
g.k.unload=function(){this.player.Z("mdxautoplaycanceled");this.Gm=this.lj;g.kf(this.Uh,this.Pb);this.Pb=this.Uh=null;g.tN.prototype.unload.call(this);this.player.Jk(5);u9(this)};
g.k.va=function(){g.Mu(this.subscriptions);g.tN.prototype.va.call(this)};
g.k.Ak=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.Uh.ej.apply(this.Uh,[a].concat(g.la(c)))};
g.k.getAdState=function(){return this.jf};
g.k.mQ=function(){return this.loaded?this.Uh.suggestion:null};
g.k.nk=function(){return this.Pb?E8(this.Pb).nk:!1};
g.k.hasNext=function(){return this.Pb?E8(this.Pb).hasNext:!1};
g.k.Rb=function(a,b){this.EJ=a||0;this.player.Z("progresssync",a,b);this.player.Ma("onVideoProgress",a)};
g.k.getCurrentTime=function(){return this.EJ};
g.k.getProgressState=function(){var a=E8(this.Pb),b=this.player.getVideoData();return{allowSeeking:g.S(this.player.T().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.gf():!a.isAdPlaying()&&this.player.gf(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.l?a.u+x8(a):a.u,isAtLiveHead:1>=(a.l?a.i+x8(a):a.i)-this.getCurrentTime(),loaded:a.L,seekableEnd:a.l?a.i+x8(a):a.i,seekableStart:0<a.B?a.B+
x8(a):a.B}};
g.k.nextVideo=function(){this.Pb&&this.Pb.nextVideo()};
g.k.fz=function(){this.Pb&&this.Pb.fz()};
g.k.kS=function(a){1===a&&(this.dE=this.Pb?E8(this.Pb):null)};
g.k.TT=function(){var a=i9()?new D8(c9(),void 0):null;if(a){var b=this.Gm;this.loaded&&this.unload();this.Pb=a;this.dE=null;b.key!==this.lj.key&&(this.Gm=b,this.load())}else g.jf(this.Pb),this.Pb=null,this.loaded&&(this.unload(),(a=this.dE)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,z8(a)));this.player.Z("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.QK=function(){var a=[this.lj],b=a.concat,c=nSa();r8()&&g.mz("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.Ln=b.call(a,c);a=d9()||this.lj;v9(this,a);this.player.Ma("onMdxReceiversChange")};
g.k.RT=function(){var a=d9();v9(this,a)};
g.k.QT=function(){this.Gm=d9()};
g.k.fV=function(){this.Iv=!0;u9(this);k9=!1;e9&&g9(e9,1);e9=null};
g.k.eV=function(){this.Iv=!1;u9(this);v9(this,this.lj);this.Gm=this.lj;k9=!1;e9=null;this.player.playVideo()};
g.k.pR=function(){this.wy=!0;u9(this);g.lz("yt-remote-manual-pairing-warning-shown",!0,2592E3);k9=!1;e9&&g9(e9,1);e9=null};
g.k.Ye=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Ln;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?t8():v9(this,b)),this.loaded?this.Gm:this.lj;case "quickCast":return 2===this.Ln.length&&"cast-selector-receiver"===this.Ln[1].key?(b&&t8(),!0):!1}};
g.k.YE=function(){this.Pb.YE()};
g.k.Gi=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.EN.remote=t9;})(_yt_player);
